'use client';

import { useEffect, useState } from 'react';
import { profileService } from '@/shared/services/profile.service';
import logger from '@/shared/utils/logger';

/**
 * Provides the current user's tenant university's canonical/display
 * affiliation name — dynamically generated by the backend affiliation
 * engine from the Super Admin-configured university name — instead of a
 * hardcoded string like "ResearchSphere" or "SGT University".
 *
 * Falls back to `fallback` (default: "University") while loading or if the
 * request fails, so forms remain usable offline.
 */
export function useAffiliation(fallback = 'University') {
  const [canonicalName, setCanonicalName] = useState<string>(fallback);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let mounted = true;
    profileService
      .getAffiliationVariants()
      .then((data) => {
        if (mounted && data?.canonicalName) {
          setCanonicalName(data.canonicalName);
        }
      })
      .catch((error) => {
        logger.error('Failed to load affiliation for form defaults:', error);
      })
      .finally(() => {
        if (mounted) setLoading(false);
      });
    return () => {
      mounted = false;
    };
  }, []);

  return { canonicalName, loading };
}
