/**
 * @module reports/services/naacWorkbook
 * @description NAAC Criterion III (Research, Innovations and Extension) data-template workbook.
 * Column headers follow the NAAC SSR data templates (revised framework metric numbering:
 * 3.1.1 grants, 3.2.2 workshops, 3.3.1 papers, 3.3.2 books/chapters/proceedings,
 * 3.4 extension, 3.5 collaboration/MoUs).
 */
const { createWorkbook, addTableSheet, addReadMeSheet, FALLBACK_FILL, INR_FORMAT, LAKH_FORMAT, toLakhs } = require('./workbook');
const { fyLabel, yearLabel } = require('../utils/period');

const pct = (part, whole) => (whole ? `${Math.round((part / whole) * 1000) / 10}%` : 'n/a');

const perTeacherColumns = (years, basis) => [
  { header: 'Name of the teacher', key: 'name', width: 30 },
  { header: 'Employee ID', key: 'empId', width: 14 },
  { header: 'Designation', key: 'designation', width: 22 },
  { header: 'Department', key: 'department', width: 30 },
  ...years.map((y) => ({ header: yearLabel(y, basis), key: `y${y}`, width: 10 })),
  { header: 'Total', key: 'total', width: 10 },
];

const perTeacherRows = (counts, years) =>
  counts.rows.map(({ teacher, counts: c, total }) => ({
    name: teacher.name,
    empId: teacher.empId,
    designation: teacher.designation,
    department: teacher.department,
    total,
    ...Object.fromEntries(years.map((y) => [`y${y}`, c[y]])),
  }));

const perTeacherFooter = (totals, years, label, basis) => [
  ['Year', ...years.map((y) => yearLabel(y, basis)), 'Total'],
  [`Number of ${label} (unique)`, ...totals.map((t) => t.count), totals.reduce((s, t) => s + t.count, 0)],
  ['Full-time teachers in post (approx.)', ...totals.map((t) => t.teachers), ''],
  ['Per teacher (unique items ÷ teachers in post)', ...totals.map((t) => (t.perTeacher === null ? 'n/a' : t.perTeacher)), ''],
];

/**
 * Build the workbook.
 * @param {object} d dataset from reports.service.buildNaacDataset
 * @returns {import('exceljs').Workbook}
 */
const buildNaacWorkbook = (d) => {
  const { university, years, paperBasis, grantBasis } = d;
  const wb = createWorkbook(`NAAC Criterion 3 — ${university.name}`);
  const rangeText = `${years[0]}–${years[years.length - 1]}`;

  // ── Read me (first sheet) ────────────────────────────────────────────────
  const pq = d.paperQuality;
  const gq = d.grantQuality;
  const fallbackFundingRows = d.funding.rows.filter((r) => r.isFallback).length;
  addReadMeSheet(wb, 'NAAC Criterion III — Research, Innovations and Extension', [
    ['Institution', `${university.name} (${university.code})`],
    ['Generated on', d.generatedAt.toISOString().replace('T', ' ').slice(0, 19) + ' UTC'],
    ['Year range', `${rangeText}. Papers/books: ${paperBasis === 'calendar' ? 'calendar years (Jan–Dec)' : 'academic years (Apr–Mar)'}. Grants: ${grantBasis === 'calendar' ? 'calendar years' : 'academic years (1 April – 31 March), e.g. 2023-24'}.`],
    ['Generated by', 'ResearchSphere (automatic export). Verify against source documents before uploading to the NAAC portal.'],
    ['Sources'],
    ['3.1.1 Grants', 'Grant applications approved/completed in DRD review that were awarded by the agency (project status "approved", or a sanction date, sanctioned amount or fund receipt is recorded). Proposals still only submitted to the agency are excluded.'],
    ['3.1 Yearwise funding', 'Fund receipts recorded against each grant, bucketed by received date into financial years. Grants without any receipt fall back to the sanctioned amount (else submitted amount) in the year of award; those rows are highlighted and marked "fallback".'],
    ['3.3.1 Papers', 'Research contributions of type "research paper" with status approved/completed, by publication date. UGC-CARE listing comes from the contribution record (set during review).'],
    ['3.3.2 Books & chapters', 'Approved/completed books, book chapters and conference proceedings papers (keynote/organiser records excluded), by publication date (conference date when no publication date).'],
    ['Per-teacher sheets', 'Teachers = accounts with role "faculty" and an employee record. A publication counts once for each teacher co-author. Teachers in post per year are approximated from join date and current active status (exit dates are not tracked).'],
    ['Template sheets', 'Sheets marked "(fill manually)" carry the NAAC column headers only: ResearchSphere does not track workshops, extension activities or MoUs.'],
    ['Data quality'],
    ['Papers in range', `${pq.total}`],
    ['Papers with unknown UGC-CARE status', `${pq.total - pq.ugcKnown} (${pct(pq.total - pq.ugcKnown, pq.total)}) — set "UGC-CARE listed" on the contribution during DRD review`],
    ['Papers without ISSN', `${pq.withoutIssn}`],
    ['Papers without DOI/link', `${pq.withoutLink}`],
    ['Papers with no teacher author', `${pq.withoutTeacher} — listed in 3.3.1 but not counted on the per-teacher sheet`],
    ['Books/chapters/proceedings with no teacher author', `${d.bookPerTeacher.unattributed}`],
    ['Approved publications with no date', `${d.undated} — cannot be placed in a year and are not in this workbook`],
    ['Grants in range', `${gq.total} (total ₹${gq.totalAmount.toLocaleString('en-IN')})`],
    ['Grants without sanctioned amount', `${gq.amountFallback} — submitted amount used where available (see Notes column)`],
    ['Grants without sanction date', `${gq.dateFallback} — year of award taken from project start or DRD approval date`],
    ['Funding rows using fallback', `${fallbackFundingRows} of ${d.funding.rows.length} (no fund receipts recorded)`],
    ['Proposals excluded (not yet awarded)', `${d.excludedProposals}`],
    ['NAAC numbering note', 'Numbering follows the NAAC revised framework used for affiliated/autonomous colleges (3.1.1, 3.2.2, 3.3.1, 3.3.2, 3.4, 3.5). In the University manual the same data maps to 3.2.1/3.2.2 (grants), 3.3.2 (workshops), 3.4.5 (papers), 3.4.6 (books), 3.6 (extension) and 3.7 (collaboration).'],
  ]);

  // ── 3.1.1 Grants ─────────────────────────────────────────────────────────
  addTableSheet(wb, '3.1.1 Grants', {
    title: '3.1.1 Grants received from Government and non-governmental agencies for research projects / endowments',
    note: `Year of award is the ${grantBasis === 'calendar' ? 'calendar' : 'academic'} year of the sanction date. Highlighted rows use a fallback (see Notes).`,
    columns: [
      { header: 'Name of the Project/ Endowments, Chairs', key: 'title', width: 46 },
      { header: 'Name of the Principal Investigator/ Co-Investigator', key: 'investigators', width: 36 },
      { header: 'Department of Principal Investigator', key: 'department', width: 30 },
      { header: 'Year of Award', key: 'yearLabel', width: 12 },
      { header: 'Amount Sanctioned (INR in Lakhs)', key: 'lakhs', width: 16, numFmt: LAKH_FORMAT },
      { header: 'Amount Sanctioned (INR)', key: 'amount', width: 16, numFmt: INR_FORMAT },
      { header: 'Duration of the project', key: 'duration', width: 14 },
      { header: 'Name of the Funding Agency', key: 'agency', width: 26 },
      { header: 'Type (Government/ Non-Government)', key: 'type', width: 16 },
      { header: 'Sanction order no.', key: 'sanctionOrderNumber', width: 18 },
      { header: 'Notes (data source)', key: 'notes', width: 40 },
    ],
    rows: d.grantRows.map((r) => ({ ...r, lakhs: toLakhs(r.amount), _fill: r.notes ? FALLBACK_FILL : undefined })),
    footer: [
      ['Year', ...years.map((y) => yearLabel(y, grantBasis))],
      ['Number of grants', ...years.map((y) => d.grantRows.filter((r) => r.year === y).length)],
      ['Amount sanctioned (INR in Lakhs)', ...years.map((y) => toLakhs(d.grantRows.filter((r) => r.year === y).reduce((s, r) => s + (r.amount || 0), 0)))],
    ],
  });

  // ── 3.1 Yearwise funding ─────────────────────────────────────────────────
  addTableSheet(wb, '3.1 Yearwise funding', {
    title: '3.1 Grants for research: amount received per year (INR)',
    note: 'From fund receipts (financial year of the received date). Highlighted rows have no receipts and show the sanctioned/submitted amount in the year of award instead.',
    columns: [
      { header: 'Name of the Project', key: 'title', width: 46 },
      { header: 'Name of the Funding Agency', key: 'agency', width: 26 },
      { header: 'Type (Government/ Non-Government)', key: 'type', width: 16 },
      ...years.map((y) => ({ header: fyLabel(y), key: `y${y}`, width: 14, numFmt: INR_FORMAT })),
      { header: 'Total (INR)', key: 'total', width: 16, numFmt: INR_FORMAT },
      { header: 'Basis', key: 'basisText', width: 34 },
      { header: 'Fallback?', key: 'fallback', width: 10 },
    ],
    rows: d.funding.rows.map((r) => ({
      ...r,
      ...Object.fromEntries(years.map((y) => [`y${y}`, r.perYear[y] || null])),
      basisText: {
        receipts: 'Fund receipts',
        sanctioned_fallback: 'Sanctioned amount (no receipts recorded)',
        submitted_fallback: 'Submitted amount (no sanction, no receipts)',
      }[r.basis] || r.basis,
      fallback: r.isFallback ? 'Y' : 'N',
      _fill: r.isFallback ? FALLBACK_FILL : undefined,
    })),
    footer: [
      ['Total received (INR)', '', '', ...years.map((y) => d.funding.totals[y]), years.reduce((s, y) => s + d.funding.totals[y], 0)],
      ['  of which fallback (INR)', '', '', ...years.map((y) => d.funding.fallbackTotals[y]), years.reduce((s, y) => s + d.funding.fallbackTotals[y], 0)],
      ['Total received (INR in Lakhs)', '', '', ...years.map((y) => toLakhs(d.funding.totals[y]))],
    ],
  });

  // ── 3.3.1 Papers ─────────────────────────────────────────────────────────
  addTableSheet(wb, '3.3.1 Papers', {
    title: '3.3.1 Number of research papers published per teacher in the Journals notified on UGC website',
    note: `${d.paperRows.length} journal papers, ${paperBasis === 'calendar' ? 'calendar' : 'academic'} years ${rangeText}. UGC-CARE "Unknown" means the listing was not recorded.`,
    columns: [
      { header: 'Title of paper', key: 'title', width: 50 },
      { header: 'Name of the author/s', key: 'authors', width: 36 },
      { header: 'Department of the teacher', key: 'department', width: 28 },
      { header: 'Name of journal', key: 'journal', width: 32 },
      { header: 'Year of publication', key: 'yearLabel', width: 12 },
      { header: 'ISSN number', key: 'issn', width: 14 },
      { header: 'Is it listed in UGC Care list (Y/N)', key: 'ugcCare', width: 14 },
      { header: 'UGC-CARE group', key: 'ugcCareGroup', width: 12 },
      { header: 'Link to article / paper / DOI', key: 'link', width: 40 },
    ],
    rows: d.paperRows.map((r) => ({ ...r, _fill: r.ugcCare === 'Unknown' ? FALLBACK_FILL : undefined })),
  });

  addTableSheet(wb, '3.3.1 Per teacher', {
    title: '3.3.1 Research papers per teacher per year',
    note: 'A paper with several teacher co-authors counts once for each. Averages use teachers in post per year (approximation from join date and active status).',
    columns: perTeacherColumns(years, paperBasis),
    rows: perTeacherRows(d.paperPerTeacher, years),
    footer: perTeacherFooter(d.paperTotals, years, 'papers', paperBasis),
  });

  // ── 3.3.2 Books & chapters ───────────────────────────────────────────────
  addTableSheet(wb, '3.3.2 Books & chapters', {
    title: '3.3.2 Number of books and chapters in edited volumes/books published and papers published in national/international conference proceedings per teacher',
    note: `${d.bookRows.length} items. "Affiliating institute" assumes the teacher was with this institution at the time of publication — verify for staff who joined later.`,
    columns: [
      { header: 'Sl. No.', key: 'sl', width: 7 },
      { header: 'Name of the teacher', key: 'teacher', width: 30 },
      { header: 'Type', key: 'kind', width: 18 },
      { header: 'Title of the book/ chapters published', key: 'bookOrChapterTitle', width: 40 },
      { header: 'Title of the book (for chapters)', key: 'bookTitle', width: 30 },
      { header: 'Title of the paper', key: 'paperTitle', width: 36 },
      { header: 'Title of the proceedings of the conference', key: 'proceedingsTitle', width: 34 },
      { header: 'Name of the conference', key: 'conferenceName', width: 30 },
      { header: 'National / International', key: 'nationalInternational', width: 14 },
      { header: 'Year of publication', key: 'yearLabel', width: 12 },
      { header: 'ISBN/ISSN number of the proceeding', key: 'isbn', width: 18 },
      { header: 'Whether at the time of publication Affiliating Institution was same', key: 'affiliatingInstitute', width: 26 },
      { header: 'Name of the publisher', key: 'publisher', width: 26 },
    ],
    rows: d.bookRows.map((r, i) => ({ ...r, sl: i + 1 })),
  });

  addTableSheet(wb, '3.3.2 Per teacher', {
    title: '3.3.2 Books, chapters and proceedings papers per teacher per year',
    note: 'An item with several teacher co-authors counts once for each.',
    columns: perTeacherColumns(years, paperBasis),
    rows: perTeacherRows(d.bookPerTeacher, years),
    footer: perTeacherFooter(d.bookTotals, years, 'books/chapters/papers', paperBasis),
  });

  // ── Templates for data the system does not track ─────────────────────────
  addTableSheet(wb, '3.2 Workshops (fill manually)', {
    template: true,
    title: '3.2.2 Number of workshops/seminars conducted on Research Methodology, Intellectual Property Rights (IPR) and entrepreneurship — TEMPLATE',
    note: 'ResearchSphere does not track workshops/seminars. Fill in manually.',
    columns: [
      { header: 'Year', key: 'a', width: 10 },
      { header: 'Name of the workshop/ seminar', key: 'b', width: 40 },
      { header: 'Number of Participants', key: 'c', width: 14 },
      { header: 'Date From – To', key: 'd', width: 22 },
      { header: 'Link to the Activity report on the website', key: 'e', width: 40 },
    ],
  });
  addTableSheet(wb, '3.4 Extension (fill manually)', {
    template: true,
    title: '3.4 Extension activities in the neighbourhood community (3.4.3 / 3.4.4) — TEMPLATE',
    note: 'ResearchSphere does not track extension and outreach programmes. Fill in manually.',
    columns: [
      { header: 'Name of the activity', key: 'a', width: 36 },
      { header: 'Organising unit/ agency/ collaborating agency', key: 'b', width: 32 },
      { header: 'Name of the scheme', key: 'c', width: 24 },
      { header: 'Year of the activity', key: 'd', width: 12 },
      { header: 'Number of students participated in such activities', key: 'e', width: 18 },
    ],
  });
  addTableSheet(wb, '3.5 Collab-MoUs (fill manually)', {
    template: true,
    title: '3.5.1 Collaborative activities / functional MoUs with institutions, industries and corporate houses — TEMPLATE',
    note: 'ResearchSphere does not track MoUs or collaborative agreements. Fill in manually.',
    columns: [
      { header: 'Sl. No.', key: 'a', width: 7 },
      { header: 'Title of the collaborative activity / Name of the organisation with whom MoU is signed', key: 'b', width: 44 },
      { header: 'Name of the collaborating agency with contact details', key: 'c', width: 34 },
      { header: 'Name of the participant', key: 'd', width: 24 },
      { header: 'Year of collaboration / signing MoU', key: 'e', width: 14 },
      { header: 'Duration', key: 'f', width: 12 },
      { header: 'Nature of the activity / list of actual activities under the MoU', key: 'g', width: 40 },
      { header: 'Link to the relevant document', key: 'h', width: 32 },
    ],
  });

  return wb;
};

module.exports = { buildNaacWorkbook };
