/**
 * @module reports/services/nirfWorkbook
 * @description NIRF "Research and Professional Practice" (RP) supporting data workbook, laid out
 * like the NIRF Data Capturing System (DCS) tables: sponsored research, consultancy, PhD,
 * patents (IPR) — plus publications/citations, which NIRF sources from Scopus/WoS itself but
 * institutions use to cross-check.
 */
const { createWorkbook, addTableSheet, addReadMeSheet, FALLBACK_FILL, INR_FORMAT } = require('./workbook');
const { fyLabel } = require('../utils/period');

const pct = (part, whole) => (whole ? `${Math.round((part / whole) * 1000) / 10}%` : 'n/a');

/** Indian-system amount in words, as the NIRF DCS asks for ("Amount received in words"). */
const ONES = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Eleven', 'Twelve',
  'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
const TENS = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
const twoDigits = (n) => (n < 20 ? ONES[n] : `${TENS[Math.floor(n / 10)]}${n % 10 ? ` ${ONES[n % 10]}` : ''}`);
const threeDigits = (n) => {
  const h = Math.floor(n / 100);
  const r = n % 100;
  return [h ? `${ONES[h]} Hundred` : '', r ? twoDigits(r) : ''].filter(Boolean).join(' ');
};
const amountInWords = (amount) => {
  let n = Math.round(Number(amount) || 0);
  if (n === 0) return 'Zero';
  const parts = [];
  const crore = Math.floor(n / 1e7);
  n %= 1e7;
  const lakh = Math.floor(n / 1e5);
  n %= 1e5;
  const thousand = Math.floor(n / 1e3);
  n %= 1e3;
  if (crore) parts.push(`${crore >= 100 ? amountInWords(crore) : twoDigits(crore)} Crore`);
  if (lakh) parts.push(`${twoDigits(lakh)} Lakh`);
  if (thousand) parts.push(`${twoDigits(thousand)} Thousand`);
  if (n) parts.push(threeDigits(n));
  return `${parts.join(' ')} Rupees`;
};

/**
 * @param {object} d dataset from reports.service.buildNirfDataset
 * @returns {import('exceljs').Workbook}
 */
const buildNirfWorkbook = (d) => {
  const { university, fyStarts } = d;
  const fyLabels = fyStarts.map(fyLabel);
  const wb = createWorkbook(`NIRF Research & Professional Practice — ${university.name}`);

  const totalPubs = d.publications.reduce((s, r) => s + r.total, 0);
  const withCites = d.publications.reduce((s, r) => s + r.withCitations, 0);
  const fallbackProjects = d.funding.rows.filter((r) => r.isFallback).length;

  addReadMeSheet(wb, 'NIRF — Research and Professional Practice (RP) data', [
    ['Institution', `${university.name} (${university.code})`],
    ['Generated on', d.generatedAt.toISOString().replace('T', ' ').slice(0, 19) + ' UTC'],
    ['Financial years', `${fyLabels.join(', ')} (1 April – 31 March)`],
    ['Generated by', 'ResearchSphere (automatic export). Verify against audited accounts and source documents before entering in the NIRF DCS.'],
    ['Sources'],
    ['Publications', 'Approved/completed journal and conference papers by financial year of publication date, classified by recorded indexing (indexing categories, "indexed in", sync sources). A paper indexed in several databases counts in each column; "Others" = no Scopus/WoS/PubMed indexing recorded. NIRF computes its own publication/citation scores from Scopus/WoS — this sheet is for cross-checking.'],
    ['Citations', 'Sum of citation counts stored by publication sync (Scopus/Crossref etc.) for papers published in each FY. Papers never synced have no count.'],
    ['Patents', 'Patent applications (IPR type "patent") counted by their own dates: filed = government filing date, published = publication date, granted = grant date. NIRF asks for calendar years for patents, so a calendar-year table is included too.'],
    ['Sponsored research', 'Awarded grants (DRD approved/completed). Amount received = fund receipts in the FY; grants without receipts fall back to the sanctioned (else submitted) amount in the FY of award — flagged. Projects = projects with money received in the FY.'],
    ['PhD', 'Students on programmes of type "doctoral". Enrolled = registered (PhD registration date, else admission date) on or before the FY end and not yet awarded; inactive students without an award date are treated as having left. Graduated = PhD awarded date within the FY. Full-time / part-time is not tracked.'],
    ['Consultancy, EDP', 'Not tracked in ResearchSphere — template sheet to fill manually.'],
    ['Data quality'],
    ['Papers in selected FYs', `${totalPubs}`],
    ['Papers with a citation count', `${withCites} of ${totalPubs} (${pct(withCites, totalPubs)}) — run publication sync for the rest`],
    ['Researcher profiles (Research Intelligence)', `${d.expertise.profiles} profiles, ${d.expertise.totalCitations.toLocaleString('en-IN')} total citations (all years, for reference)`],
    ['Approved publications with no date', `${d.undated} — not counted in any year`],
    ['Patent records', `${d.patentGaps.total} (granted: ${d.patentGaps.granted})`],
    ['Patents filed (by status) without filing date', `${d.patentGaps.filedWithoutDate}`],
    ['Patents "published" without publication date', `${d.patentGaps.publishedWithoutDate}`],
    ['Granted patents without patent number', `${d.patentGaps.grantedWithoutNumber}`],
    ['Sponsored projects using amount fallback', `${fallbackProjects} of ${d.funding.rows.length} (no fund receipts recorded)`],
    ['Doctoral students', `${d.phdGaps.total} (awarded: ${d.phdGaps.awarded})`],
    ['PhD records without registration date', `${d.phdGaps.withoutRegistrationDate} (${d.phdGaps.withoutStartDate} have neither registration nor admission date and are not counted as enrolled)`],
    ['Inactive PhD records without award date', `${d.phdGaps.inactiveWithoutAward} — excluded from enrolled; set PhD awarded date if they graduated`],
  ]);

  // ── Publications & citations ─────────────────────────────────────────────
  addTableSheet(wb, 'Publications', {
    title: 'Publications by indexing database and citations (by financial year of publication)',
    note: 'Journal + conference papers. Columns overlap: a paper in Scopus and WoS counts in both. Citation coverage = papers with a synced citation count.',
    columns: [
      { header: 'Financial Year', key: 'fy', width: 14 },
      { header: 'Total papers', key: 'total', width: 12 },
      { header: 'Scopus', key: 'scopus', width: 10 },
      { header: 'Web of Science', key: 'wos', width: 14 },
      { header: 'PubMed', key: 'pubmed', width: 10 },
      { header: 'Others (not indexed in Scopus/WoS/PubMed)', key: 'others', width: 22 },
      { header: 'Citations (sum)', key: 'citations', width: 14 },
      { header: 'Papers with citation data', key: 'withCitations', width: 16 },
      { header: 'Citation coverage', key: 'coverage', width: 14 },
    ],
    rows: d.publications.map((r) => ({ ...r, fy: fyLabel(r.year), coverage: pct(r.withCitations, r.total) })),
  });

  // ── Patents ──────────────────────────────────────────────────────────────
  const patentColumns = (label) => [
    { header: label, key: 'label', width: 16 },
    { header: 'No. of Patents Filed', key: 'filed', width: 16 },
    { header: 'No. of Patents Published', key: 'published', width: 18 },
    { header: 'No. of Patents Granted', key: 'granted', width: 16 },
  ];
  addTableSheet(wb, 'Patents (FY)', {
    title: 'IPR — Patents filed, published and granted per financial year',
    note: 'Counted by the date of each event.',
    columns: patentColumns('Financial Year'),
    rows: d.patentsFy.map((r) => ({ ...r, label: fyLabel(r.year) })),
  });
  addTableSheet(wb, 'Patents (calendar year)', {
    title: 'IPR — Patents filed, published and granted per calendar year (NIRF DCS format)',
    note: 'NIRF asks for patents by calendar year.',
    columns: patentColumns('Calendar Year'),
    rows: d.patentsCy.map((r) => ({ ...r, label: String(r.year) })),
  });

  // ── Sponsored research ───────────────────────────────────────────────────
  addTableSheet(wb, 'Sponsored Research', {
    title: 'Sponsored Research Details',
    note: 'Amounts in INR. "of which fallback" = sanctioned/submitted amounts used for projects with no fund receipts recorded.',
    columns: [
      { header: 'Financial Year', key: 'fy', width: 14 },
      { header: 'Total no. of Sponsored Projects', key: 'projects', width: 18 },
      { header: 'Total no. of Funding Agencies', key: 'agencies', width: 18 },
      { header: 'Total Amount Received (Amount in Rupees)', key: 'amount', width: 22, numFmt: INR_FORMAT },
      { header: 'Amount Received in Words', key: 'words', width: 50 },
      { header: 'of which fallback (INR)', key: 'fallbackAmount', width: 18, numFmt: INR_FORMAT },
      { header: 'Projects using fallback', key: 'fallbackProjects', width: 14 },
    ],
    rows: d.sponsored.map((r) => ({ ...r, fy: fyLabel(r.year), words: amountInWords(r.amount), _fill: r.fallbackProjects ? FALLBACK_FILL : undefined })),
  });
  addTableSheet(wb, 'Sponsored Projects (detail)', {
    title: 'Sponsored projects — amount received per financial year',
    note: 'Highlighted rows have no fund receipts; the sanctioned (else submitted) amount is shown in the FY of award.',
    columns: [
      { header: 'Name of the Project', key: 'title', width: 46 },
      { header: 'Funding Agency', key: 'agency', width: 26 },
      { header: 'Type (Government/ Non-Government)', key: 'type', width: 16 },
      ...fyStarts.map((y) => ({ header: fyLabel(y), key: `y${y}`, width: 14, numFmt: INR_FORMAT })),
      { header: 'Total (INR)', key: 'total', width: 16, numFmt: INR_FORMAT },
      { header: 'Fallback?', key: 'fallback', width: 10 },
    ],
    rows: d.funding.rows.map((r) => ({
      ...r,
      ...Object.fromEntries(fyStarts.map((y) => [`y${y}`, r.perYear[y] || null])),
      fallback: r.isFallback ? 'Y' : 'N',
      _fill: r.isFallback ? FALLBACK_FILL : undefined,
    })),
  });

  // ── Consultancy (template) ───────────────────────────────────────────────
  addTableSheet(wb, 'Consultancy (fill manually)', {
    template: true,
    title: 'Consultancy Project Details — TEMPLATE',
    note: 'ResearchSphere does not track consultancy projects. Fill in manually from the accounts section.',
    columns: [
      { header: 'Financial Year', key: 'a', width: 14 },
      { header: 'Total no. of Consultancy Projects', key: 'b', width: 18 },
      { header: 'Total no. of Client Organizations', key: 'c', width: 18 },
      { header: 'Total Amount Received (Amount in Rupees)', key: 'd', width: 22 },
      { header: 'Amount Received in Words', key: 'e', width: 44 },
    ],
  });

  // ── PhD ──────────────────────────────────────────────────────────────────
  const last = d.phd[d.phd.length - 1];
  addTableSheet(wb, 'PhD Students', {
    title: 'Ph.D Student Details',
    note: `Full-time / part-time is not recorded in ResearchSphere: totals are given in the "Total" column — split them manually. Enrolled = pursuing at the end of each FY.`,
    columns: [
      { header: 'Financial Year', key: 'fy', width: 14 },
      { header: 'Pursuing PhD — Full Time', key: 'ft', width: 16 },
      { header: 'Pursuing PhD — Part Time', key: 'pt', width: 16 },
      { header: 'Pursuing PhD — Total (FT/PT not tracked)', key: 'enrolled', width: 22 },
      { header: 'No. of Ph.D students graduated — Full Time', key: 'gft', width: 20 },
      { header: 'No. of Ph.D students graduated — Part Time', key: 'gpt', width: 20 },
      { header: 'No. of Ph.D students graduated — Total', key: 'graduated', width: 20 },
    ],
    rows: d.phd.map((r) => ({ ...r, fy: fyLabel(r.year), ft: null, pt: null, gft: null, gpt: null })),
    footer: last ? [[`Total students pursuing doctoral program till ${fyLabel(last.year)}`, '', '', last.enrolled]] : [],
  });

  return wb;
};

module.exports = { buildNirfWorkbook, amountInWords };
