'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi'; // English, Hindi

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Common
    'common.selectPurpose': 'Select Purpose',
    'common.allStatus': 'All Status',
    'common.allDates': 'All Dates',
    'common.allPurposes': 'All Purposes',
    'common.allTypes': 'All Types',
    'common.enterFullName': 'Enter full name',
    'common.tenDigitNumber': '10-digit number',
    'common.visitorExample': 'visitor@example.com',
    'common.relationExample': 'e.g., Friend, Family, Vendor',
    'common.passIdNameMobile': 'Pass ID, Name, Mobile, Relation, Vehicle...',
    'common.of': 'of',
    'common.passes': 'passes',
    
    // Create Pass Page
    'createPass.title': 'Create Visitor Pass',
    'createPass.subtitle': 'Generate secure entry passes for campus visitors',
    'createPass.creatingAs': 'Creating as:',
    'createPass.parentGuardianOnly': 'Parent/Guardian Only',
    'createPass.visitorInfo': 'Visitor Information',
    'createPass.visitorInfoDesc': "Enter visitor's personal details",
    'createPass.visitorName': 'Visitor Name',
    'createPass.mobileNumber': 'Mobile Number',
    'createPass.emailAddress': 'Email Address',
    'createPass.relation': 'Relation',
    'createPass.numberOfPersons': 'Number of Persons',
    'createPass.totalVisitors': 'Total number of visitors (including you)',
    'createPass.visitDetails': 'Visit Details',
    'createPass.visitDetailsDesc': 'Schedule and purpose of visit',
    'createPass.purposeOfVisit': 'Purpose of Visit',
    'createPass.visitStartDate': 'Visit Start Date',
    'createPass.visitEndDate': 'Visit End Date',
    'createPass.entryTime': 'Entry Time',
    'createPass.vehicleInfo': 'Vehicle Information',
    'createPass.vehicleInfoDesc': 'Optional vehicle registration details',
    'createPass.vehicleType': 'Vehicle Type',
    'createPass.vehicleNumber': 'Vehicle Number',
    'createPass.vehicleModel': 'Vehicle Model',
    'createPass.accommodation': 'Accommodation',
    'createPass.accommodationDesc': 'Hostel/Apartment booking for multi-day stay',
    'createPass.cancel': 'Cancel',
    'createPass.createPass': 'Create Pass',
    'createPass.creating': 'Creating Pass...',
    'createPass.whatsappNotification': 'Visitor will receive WhatsApp notification',
    'createPass.emailNotification': 'QR code & pass details will be sent via email',
    'createPass.selectGuardian': 'Select Guardian/Parent',
    'createPass.selectGuardianOption': '-- Select Guardian --',
    'createPass.selectFromGuardians': 'Select from your registered guardians or enter manually below',
    'createPass.loadingGuardians': 'Loading your guardians...',
    'createPass.noGuardiansFound': 'No guardians found in database. Please enter details manually below.',
    'createPass.autoFilled': 'Auto-filled from guardian selection',
    'createPass.parentGuardianBadge': 'Parent/Guardian Only',
    'createPass.howManyPeople': 'How many people',
    'createPass.specifyPurpose': 'Specify Purpose',
    'createPass.enterPurpose': 'Enter purpose',
    'createPass.selectRelation': 'Select Relation',
    'createPass.father': 'Father',
    'createPass.mother': 'Mother',
    'createPass.guardian': 'Guardian',
    'createPass.parentOther': 'Parent (Other)',
    'createPass.multiDayStayDetected': 'Multi-day stay detected - hostel/apartment booking available below',
    'createPass.entry': 'Entry:',
    'createPass.qrActivates': 'QR activates 5 hours before',
    'createPass.visitorWillBringVehicle': 'Visitor will bring a vehicle',
    'createPass.vehicleNumberExample': 'e.g., DL01AB1234',
    'createPass.vehicleModelExample': 'e.g., Honda City, Yamaha R15',
    'createPass.noVehicleRequired': 'No vehicle information required',
    'createPass.multiDayVisitDetected': 'Multi-day visit detected',
    'createPass.visitPeriod': 'Visit Period:',
    'createPass.qrActivation': 'QR Activation:',
    'createPass.qrExpiry': 'QR Expiry:',
    'createPass.bookHostelQuestion': 'Do you want to book Hostel/Apartment?',
    'createPass.yesBooking': '✅ Yes, I want to book',
    'createPass.browseRooms': 'Browse & book from available rooms/apartments',
    'createPass.bookingFlowOpens': 'Booking flow opens after pass creation',
    'createPass.noSkipBooking': '❌ No, skip booking',
    'createPass.continueWithoutBooking': 'Continue without accommodation booking',
    'createPass.duplicateFound': '⚠️ Cannot Create Pass - Duplicate Found',
    'createPass.cancelExisting': 'Please cancel or complete the existing pass before creating a new one.',
    'createPass.viewExistingPasses': 'View & Manage Existing Passes →',
    'createPass.checkingDuplicate': 'Checking for duplicate passes...',
    'createPass.error': 'Error',
    // Purpose options - Student
    'createPass.studentPurpose.personal': 'Family Visit',
    'createPass.studentPurpose.meeting': 'Meeting with Student',
    'createPass.studentPurpose.event': 'University Event',
    'createPass.studentPurpose.emergency': 'Emergency',
    'createPass.studentPurpose.other': 'Other',
    // Purpose options - General
    'createPass.generalPurpose.meeting': 'Meeting',
    'createPass.generalPurpose.personal': 'Personal Visit',
    'createPass.generalPurpose.delivery': 'Delivery',
    'createPass.generalPurpose.event': 'Event',
    'createPass.generalPurpose.vendor': 'Vendor/Service',
    'createPass.generalPurpose.other': 'Other',
    // Vehicle types
    'createPass.vehicleType.two_wheeler': 'Two Wheeler',
    'createPass.vehicleType.four_wheeler': 'Four Wheeler',
    'createPass.vehicleType.other': 'Other',
    'createPass.selectVehicleType': 'Select Vehicle Type',
    // Validation errors
    'createPass.err.visitorNameRequired': 'Visitor name is required',
    'createPass.err.invalidMobile': 'Valid 10-digit mobile number is required',
    'createPass.err.invalidEmail': 'Please enter a valid email address',
    'createPass.err.personsMin': 'Number of persons must be at least 1',
    'createPass.err.personsMax': 'Number of persons cannot exceed 50',
    'createPass.err.purposeRequired': 'Purpose of visit is required',
    'createPass.err.specifyOther': 'Please specify other purpose',
    'createPass.err.datesRequired': 'Visit dates are required',
    'createPass.err.endDateBeforeStart': 'End date cannot be before start date',
    'createPass.err.entryTimeRequired': 'Entry time is required',
    'createPass.err.pastTimeNotAllowed': 'Entry time cannot be in the past. Please select current or future time.',
    'createPass.err.vehicleNumberRequired': 'Vehicle number is required when bringing vehicle',
    'createPass.err.vehicleModelRequired': 'Vehicle model is required when bringing vehicle',
    'createPass.err.accommodationRequired': 'Please indicate if you want to book accommodation',
    // Success modal
    'createPass.successTitle': 'Pass Created Successfully!',
    'createPass.successMessage': 'Share this code with your visitor for entry verification.',
    'createPass.successMessageHostel': 'Now book accommodation for the visitor.',
    'createPass.successPassId': 'Pass ID',
    'createPass.successVerifCode': 'Verification Code',
    'createPass.successOk': 'OK, Got It!',
    'createPass.successShareNote': '🔐 Share the verification code with your visitor for entry',
    'createPass.successWhatsappSent': '📱 WhatsApp sent to',
    'createPass.successEmailSent': '📧 Email sent to',
    // Hostel Booking Flow
    'hostel.title': 'Hostel Booking',
    'hostel.multiDayQuestion': 'Your visit is multi-day. Do you need accommodation?',
    'hostel.needAccommodation': 'I need to book accommodation',
    'hostel.browseHostels': 'Browse available hostels and rooms',
    'hostel.noAccommodation': 'No accommodation needed',
    'hostel.continueWithout': 'Continue without hostel booking',
    'hostel.selectHostel': 'Select Hostel',
    'hostel.selectRoom': 'Select Room',
    'hostel.back': '← Back',
    'hostel.loadingHostels': 'Loading hostels...',
    'hostel.loadingRooms': 'Loading rooms...',
    'hostel.noHostels': 'No hostels available for selected dates',
    'hostel.noRooms': 'No rooms available in this hostel',
    'hostel.roomsAvailable': 'rooms available',
    'hostel.room': 'Room',
    'hostel.maxGuests': 'Max',
    'hostel.guests': 'guests',
    'hostel.guest': 'guest',
    'hostel.nights': 'nights',
    'hostel.night': 'night',
    'hostel.pricePerNight': '/night',
    
    // All Passes Page
    'allPasses.title': 'All Gate Passes',
    'allPasses.adminView': 'Admin View: Showing all gate passes',
    'allPasses.guardView': 'Guard View: Showing all gate passes for verification',
    'allPasses.myPasses': 'My Passes: Showing only passes created by you',
    'allPasses.refresh': 'Refresh',
    'allPasses.createNew': 'Create New Pass',
    'allPasses.totalPasses': 'Total Passes',
    'allPasses.activeToday': 'Active Today',
    'allPasses.pending': 'Pending',
    'allPasses.completed': 'Completed',
    'allPasses.expired': 'Expired',
    'allPasses.filterSearch': 'Filter & Search Passes',
    'allPasses.searchPasses': 'Search Passes',
    'allPasses.status': 'Status',
    'allPasses.dateRange': 'Date Range',
    'allPasses.exportCSV': 'Export to CSV',
    // Status filter options
    'allPasses.filter.pending': 'Pending (Not Completed)',
    'allPasses.filter.active': 'Active',
    'allPasses.filter.checkedIn': 'Checked In',
    'allPasses.filter.completed': 'Completed',
    'allPasses.filter.denied': 'Denied',
    'allPasses.filter.expired': 'Expired',
    'allPasses.filter.cancelled': 'Cancelled',
    // Date filter options
    'allPasses.filter.today': 'Today',
    'allPasses.filter.upcoming': 'Upcoming',
    'allPasses.filter.past': 'Past',
    // Status badge labels
    'allPasses.status.created': 'Created',
    'allPasses.status.checked_in': 'Checked In',
    'allPasses.status.cancelled': 'Cancelled',
    'allPasses.status.checked_out': 'Checked Out',
    'allPasses.status.expired': 'Expired',
    'allPasses.status.pending': 'Pending',
    'allPasses.status.active': 'Active',
    'allPasses.status.completed': 'Completed',
    'allPasses.status.denied': 'Denied',
    // Table headers
    'allPasses.col.passId': 'Pass ID',
    'allPasses.col.visitorDetails': 'Visitor Details',
    'allPasses.col.visitInfo': 'Visit Info',
    'allPasses.col.dateTime': 'Date & Time',
    'allPasses.col.status': 'Status',
    'allPasses.col.actions': 'Actions',
    // Table content
    'allPasses.noPassesFound': 'No passes found matching your filters',
    'allPasses.by': 'by',
    'allPasses.system': 'System',
    'allPasses.persons': 'persons',
    'allPasses.multiDayStay': 'Multi-day stay:',
    'allPasses.in': '\u2713 In:',
    'allPasses.out': 'Out:',
    // Loading / error
    'allPasses.loading': 'Loading gate passes...',
    'allPasses.loadingWait': 'Please wait while we fetch your data',
    'allPasses.errorTitle': 'Error Loading Passes',
    'allPasses.tryAgain': 'Try Again',
    // Action tooltips
    'allPasses.action.viewDetails': 'View Details',
    'allPasses.action.cancelPass': 'Cancel Pass',
    'allPasses.action.resendNotif': 'Resend Notification',
    // Detail modal
    'allPasses.detail.title': 'Pass Details',
    'allPasses.detail.visitorInfo': 'Visitor Information',
    'allPasses.detail.visitInfo': 'Visit Information',
    'allPasses.detail.vehicleInfo': 'Vehicle Information',
    'allPasses.detail.stayInfo': 'Stay Information',
    'allPasses.detail.entryExitRecords': 'Entry/Exit Records',
    'allPasses.detail.extensionInfo': 'Pass Extension Information',
    'allPasses.detail.checkoutQr': 'Checkout QR Code (1 Hour Validity)',
    'allPasses.detail.name': 'Name:',
    'allPasses.detail.mobile': 'Mobile:',
    'allPasses.detail.email': 'Email:',
    'allPasses.detail.relation': 'Relation:',
    'allPasses.detail.persons': 'Number of Persons:',
    'allPasses.detail.purpose': 'Purpose:',
    'allPasses.detail.visitDate': 'Visit Date:',
    'allPasses.detail.endDate': 'End Date:',
    'allPasses.detail.entryTime': 'Entry Time:',
    'allPasses.detail.exitTime': 'Exit Time:',
    'allPasses.detail.totalDuration': 'Total Duration:',
    'allPasses.detail.qrActivates': 'QR Activates:',
    'allPasses.detail.vehicleNumber': 'Vehicle Number:',
    'allPasses.detail.vehicleType': 'Vehicle Type:',
    'allPasses.detail.vehicleModel': 'Vehicle Model:',
    'allPasses.detail.checkInDate': 'Check-in Date:',
    'allPasses.detail.checkOutDate': 'Check-out Date:',
    'allPasses.detail.hostel': 'Hostel:',
    'allPasses.detail.roomNumber': 'Room Number:',
    'allPasses.detail.expires': 'Expires:',
    'allPasses.detail.qrValid1h': '\u23f0 Valid for 1 hour only. Visitor must exit within this time.',
    'allPasses.detail.extended': 'Extended:',
    'allPasses.detail.times': 'time(s)',
    'allPasses.detail.reason': 'Reason:',
    'allPasses.detail.notProvided': 'Not provided',
    'allPasses.detail.createdAt': 'Created At:',
    'allPasses.detail.createdBy': 'Created By:',
    'allPasses.detail.unknown': 'Unknown',
    'allPasses.detail.extendPass': 'Extend Pass',
    'allPasses.detail.resendNotif': 'Resend Notification',
    'allPasses.detail.close': 'Close',
    // Cancel modal
    'allPasses.cancel.title': 'Cancel Pass',
    'allPasses.cancel.warning': 'Warning: Cancelling this pass will generate a checkout QR code (valid for 1 hour) that will be sent to the visitor\u2019s mobile/email. The visitor must exit the premises within 1 hour using this QR code.',
    'allPasses.cancel.passDetails': 'Pass Details',
    'allPasses.cancel.passId': 'Pass ID:',
    'allPasses.cancel.visitor': 'Visitor:',
    'allPasses.cancel.mobile': 'Mobile:',
    'allPasses.cancel.status': 'Status:',
    'allPasses.cancel.reasonLabel': 'Cancellation Reason',
    'allPasses.cancel.reasonPlaceholder': 'Enter reason for cancelling this pass...',
    'allPasses.cancel.keepPass': 'No, Keep Pass',
    'allPasses.cancel.confirm': 'Yes, Cancel Pass',
    'allPasses.cancel.cancelling': 'Cancelling...',
    'allPasses.cancel.successTitle': 'Pass Cancelled Successfully!',
    'allPasses.cancel.successMessage': 'Emergency checkout QR and code sent to visitor (valid for 1 hour).',
    'allPasses.cancel.noReason': 'Please provide a cancellation reason',
    'allPasses.cancel.reasonRequired': 'Reason Required',
    'allPasses.cancel.failedMsg': 'Failed to cancel pass',
    // Cancel Pass - Refund Details
    'allPasses.cancel.beforeCheckIn': 'Cancel Before Check-in',
    'allPasses.cancel.afterCheckIn': 'Cancel After Check-in (Checkout QR)',
    'allPasses.cancel.refundDetails': 'Refund Details',
    'allPasses.cancel.originalAmount': 'Original Amount',
    'allPasses.cancel.cancellationFee': 'Cancellation Fee ({percent}%)',
    'allPasses.cancel.refundAmount': 'Refund Amount',
    'allPasses.cancel.hostelBookingInfo': 'Hostel Booking Information',
    'allPasses.cancel.roomNumber': 'Room Number',
    'allPasses.cancel.hostelName': 'Hostel Name',
    'allPasses.cancel.noRefund': 'No hostel booking - no refund applicable',
    'allPasses.cancel.warningBeforeCheckIn': 'Note: This pass has not been checked in yet. Cancelling will not generate a checkout QR code.',
    'allPasses.cancel.warningAfterCheckIn': 'Warning: Cancelling this pass will generate a checkout QR code (valid for 1 hour) that will be sent to the visitor\u2019s mobile/email.',
    'allPasses.cancel.successBeforeCheckIn': 'Pass cancelled successfully',
    'allPasses.cancel.successWithRefund': 'Pass cancelled. Refund amount: ₹{amount}',
    'allPasses.cancel.reasonRequiredError': 'Cancellation reason is required',
    // Resend notification
    'allPasses.resend.title': 'Notification Sent',
    'allPasses.resend.message': 'Notification resent to',
    // Extend Pass Modal
    'extend.title': 'Extend Pass',
    'extend.note': 'Note: Extending the end date will update the pass expiry time to the new end date at 23:59. QR code expiration will be updated automatically.',
    'extend.currentDetails': 'Current Details',
    'extend.passId': 'Pass ID:',
    'extend.visitStartDate': 'Visit Start Date:',
    'extend.currentEndDate': 'Current End Date:',
    'extend.entryTime': 'Entry Time:',
    'extend.newEndDate': 'New End Date',
    'extend.expireNote': 'Pass will expire at 23:59 on this date',
    'extend.reasonLabel': 'Extension Reason',
    'extend.reasonPlaceholder': 'Please provide a reason for extending the pass...',
    'extend.cancel': 'Cancel',
    'extend.submit': 'Extend Pass',
    'extend.submitting': 'Extending...',
    'extend.errNoDate': 'Please select new end date',
    'extend.errNoReason': 'Please provide a reason for extension',
    'extend.errDateAfter': 'New end date must be after current end date',
    'extend.errFailed': 'Failed to extend pass',
    'extend.successTitle': 'Pass Extended!',
    'extend.successMsg': 'Pass end date extended successfully',
    'common.error': 'Error',
    
    // Verify Pass Page
    'verifyPass.title': 'Pass Verification',
    'verifyPass.subtitle': 'Guard interface for visitor pass verification and entry management',
    'verifyPass.manualSearch': 'Manual Search',
    'verifyPass.qrScan': 'QR Scan',
    'verifyPass.searchBy': 'Search By',
    'verifyPass.search': 'Search',
    'verifyPass.searching': 'Searching...',
    'verifyPass.scannerCamera': 'Scanner Camera',
    'verifyPass.positionQR': 'Position the QR code within the camera frame',
    'verifyPass.verifying': 'Verifying scanned pass...',
    'verifyPass.enterPassId': 'Enter Pass ID',
    'verifyPass.passIdPlaceholder': 'UNI-PASS-XXX',
    
    // Verify Pass - Search Options
    'verifyPass.searchOptions.passId': 'Pass ID',
    'verifyPass.searchOptions.visitorName': 'Visitor Name',
    'verifyPass.searchOptions.mobile': 'Mobile Number',
    'verifyPass.searchOptions.vehicle': 'Vehicle Number',
    'verifyPass.enterVisitorName': 'Enter Visitor Name',
    'verifyPass.enterMobile': 'Enter Mobile Number',
    'verifyPass.enterVehicle': 'Enter Vehicle Number',
    'verifyPass.placeholderName': 'Name',
    'verifyPass.placeholderMobile': 'Mobile',
    'verifyPass.placeholderVehicle': 'Vehicle No.',
    
    // Verify Pass - Errors
    'verifyPass.err.checkoutQrNotFound': 'Pass not found for checkout QR',
    'verifyPass.err.passNotFound': 'Pass not found',
    'verifyPass.err.invalidQR': 'Invalid QR Code or Pass not found',
    'verifyPass.err.searchTermRequired': 'Please enter a search term',
    'verifyPass.err.noPassFound': 'No pass found matching your search criteria',
    'verifyPass.err.verificationFailed': 'Verification Failed',
    
    // Status Labels
    'status.created': 'Created',
    'status.pending': 'Pending',
    'status.active': 'Active',
    'status.checkedIn': 'Checked In',
    'status.completed': 'Completed',
    'status.checkedOut': 'Checked Out',
    'status.cancelled': 'Cancelled',
    'status.expired': 'Expired',
    'status.denied': 'Denied',
    
    // Verify Pass - Toast Notifications
    'verifyPass.toast.checkinSuccess': 'Visitor has been checked in successfully!',
    'verifyPass.toast.checkinSuccessTitle': 'Entry Allowed',
    'verifyPass.toast.checkinFailed': 'Failed to allow entry',
    'verifyPass.toast.codeRequired': 'Please enter the verification code',
    'verifyPass.toast.codeRequiredTitle': 'Verification Required',
    'verifyPass.toast.invalidCode': 'Invalid verification code. Please try again.',
    'verifyPass.toast.invalidCodeTitle': 'Verification Failed',
    'verifyPass.toast.entryDenied': 'Pass has been marked as denied',
    'verifyPass.toast.entryDeniedTitle': 'Entry Denied',
    'verifyPass.toast.denyFailed': 'Failed to deny entry',
    'verifyPass.toast.exitSuccess': 'Visitor has been checked out successfully!',
    'verifyPass.toast.exitSuccessTitle': 'Exit Recorded',
    'verifyPass.toast.exitFailed': 'Failed to record exit',
    'verifyPass.toast.checkoutSuccessTitle': 'Checkout Recorded',
    'verifyPass.toast.checkoutFailed': 'Failed to record checkout',
    'verifyPass.toast.checkoutCodeInvalid': 'Invalid checkout verification code. Please use the NEW code sent after cancellation.',
    'verifyPass.toast.reasonRequired': 'Please enter cancellation reason',
    'verifyPass.toast.reasonRequiredTitle': 'Reason Required',
    'verifyPass.toast.cancelSuccess': 'Pass cancelled successfully. Checkout credentials generated!',
    'verifyPass.toast.cancelSuccessTitle': 'Pass Cancelled',
    'verifyPass.toast.cancelFailed': 'Failed to cancel pass',
    'verifyPass.toast.idCopied': 'Checkout ID copied!',
    'verifyPass.toast.codeCopied': 'Checkout code copied!',
    'verifyPass.toast.copied': 'Copied',
    'verifyPass.toast.cancelledPassWarning': '⚠️ CANCELLED PASS - Checkout Required',
    
    // Verify Pass - QR Scanner
    'verifyPass.qr.initializing': 'Initializing camera scanner...',
    'verifyPass.qr.instructions': 'Scanning Instructions:',
    'verifyPass.qr.step1': 'Camera selection dropdown will appear above - select your camera',
    'verifyPass.qr.step2': 'Click the "Start Scanning" button to open camera',
    'verifyPass.qr.step3': 'Hold visitor\'s gate pass QR code in front of camera',
    'verifyPass.qr.tip1': 'Ensure good lighting and steady hand for faster detection',
    'verifyPass.qr.tip2': 'Scanner will automatically verify pass after successful scan',
    'verifyPass.qr.tip3': 'Allow camera permission when browser prompts',
    'verifyPass.qr.tip4': 'Switch to Manual Search tab if QR code is not readable',
    
    // Verify Pass - Details
    'verifyPass.details.passId': 'Pass ID',
    'verifyPass.details.visitorInfo': 'Visitor Information',
    'verifyPass.details.visitInfo': 'Visit Information',
    'verifyPass.details.vehicleInfo': 'Vehicle Information',
    'verifyPass.details.additionalInfo': 'Additional Information',
    'verifyPass.details.entryExitRecords': 'Entry/Exit Records',
    'verifyPass.details.guardActions': 'Guard Actions',
    
    // Verify Pass - Fields
    'verifyPass.fields.name': 'Name',
    'verifyPass.fields.mobile': 'Mobile',
    'verifyPass.fields.email': 'Email',
    'verifyPass.fields.idProof': 'ID Proof',
    'verifyPass.fields.genderAge': 'Gender / Age',
    'verifyPass.fields.years': 'years',
    'verifyPass.fields.persons': 'Number of Persons',
    'verifyPass.fields.purpose': 'Purpose',
    'verifyPass.fields.department': 'Department',
    'verifyPass.fields.personToMeet': 'Person to Meet',
    'verifyPass.fields.visitDate': 'Visit Date',
    'verifyPass.fields.entryTime': 'Entry Time',
    'verifyPass.fields.qrActivatesAt': 'QR Activates At',
    'verifyPass.fields.vehicleNumber': 'Vehicle Number',
    'verifyPass.fields.vehicleType': 'Vehicle Type',
    'verifyPass.fields.vehicleModel': 'Vehicle Model',
    'verifyPass.fields.itemsCarrying': 'Items Carrying',
    'verifyPass.fields.specialInstructions': 'Special Instructions',
    'verifyPass.fields.actualEntryTime': 'Actual Entry Time',
    'verifyPass.fields.actualExitTime': 'Actual Exit Time',
    
    // Verify Pass - Warnings
    'verifyPass.warnings.expiringSoon': '⏰ EXPIRING SOON!',
    'verifyPass.warnings.lessThan15': '⚠️ Less than 15 min',
    'verifyPass.warnings.valid': '✅ Valid',
    'verifyPass.warnings.expired': 'EXPIRED',
    'verifyPass.warnings.remaining': 'Remaining',
    'verifyPass.warnings.cancelledAt': 'Cancelled At:',
    'verifyPass.warnings.qrNotActive': '⏰ QR Code Not Yet Active',
    'verifyPass.warnings.qrNotActiveMsg': 'This QR code will activate 5 hours before entry time',
    'verifyPass.warnings.activationTime': 'Activation Time:',
    'verifyPass.warnings.qrActive': '✅ Pass Verified - QR Active',
    'verifyPass.warnings.qrActiveMsg': 'QR code is active. Please verify visitor ID proof and details below before allowing entry.',
    'verifyPass.warnings.checkoutRequired': '⚠️ CHECKOUT - CANCELLED PASS',
    'verifyPass.warnings.checkoutMsg': 'This pass has been cancelled. A 1-hour checkout QR code was issued to the visitor.',
    'verifyPass.warnings.checkoutNote': 'Verify visitor identity and allow exit using the "Record Checkout" button below.',
    'verifyPass.warnings.qrValidity': 'Checkout QR Validity',
    
    // Verify Pass - Actions
    'verifyPass.actions.processing': 'Processing...',
    'verifyPass.actions.recordCheckout': '🚨 Record Checkout',
    'verifyPass.actions.qrExpired': '❌ Checkout QR Expired - Contact Admin to Regenerate',
    'verifyPass.actions.allowEntry': 'Allow Entry',
    'verifyPass.actions.qrWillActivate': '⏰ QR will activate 5 hours before entry time',
    'verifyPass.actions.recordExit': 'Record Exit',
    'verifyPass.actions.denyEntry': 'Deny Entry',
    'verifyPass.actions.alreadyCompleted': '✅ Pass Already Completed',
    'verifyPass.actions.passExpired': '⏰ Pass Expired',
    'verifyPass.actions.passRejected': '❌ Pass Rejected',
    'verifyPass.actions.noActions': 'ℹ️ No Actions Available',
    
    // Verify Pass - Guard Messages
    'verifyPass.guard.checkoutMsg': '🚨 CHECKOUT - Record visitor exit',
    'verifyPass.guard.allowEntryMsg': '✅ Verify visitor ID proof before allowing entry',
    'verifyPass.guard.recordExitMsg': '✅ Confirm visitor is leaving premises',
    'verifyPass.guard.denyEntryMsg': '⚠️ Deny entry if verification fails',
    'verifyPass.guard.noActionsMsg': 'ℹ️ No actions available - pass already processed',
    
    // Verify Pass - Verification Modal
    'verifyPass.modal.verifyIdentity': '🔐 Verify Visitor Identity',
    'verifyPass.modal.chooseMethod': 'Choose verification method',
    'verifyPass.modal.identityRequired': 'Visitor Identity Verification Required',
    'verifyPass.modal.identityMsg': 'Before allowing entry, verify the visitor\'s identity using one of the methods below.',
    'verifyPass.modal.scanQR': 'Scan QR Code',
    'verifyPass.modal.scanQRMsg': 'Ask visitor to show QR code from their gate pass',
    'verifyPass.modal.openCamera': 'Open Camera',
    'verifyPass.modal.enterCode': 'Enter Code',
    'verifyPass.modal.enterCodeMsg': 'Ask visitor for their 6-digit verification code',
    'verifyPass.modal.backToOptions': '← Back to options',
    'verifyPass.modal.scanVisitorQR': 'Scan Visitor\'s QR Code',
    'verifyPass.modal.positionQR': 'Ask the visitor to show their gate pass QR code. Position it within the camera frame.',
    'verifyPass.modal.verifyingEntry': 'Verifying and allowing entry...',
    'verifyPass.modal.enter6Digit': 'Enter 6-Digit Verification Code',
    'verifyPass.modal.ask6Digit': 'Ask the visitor to provide the 6-digit code they received with their gate pass.',
    'verifyPass.modal.verificationCode': 'Verification Code',
    'verifyPass.modal.enter6DigitPlaceholder': 'Enter 6-digit code',
    'verifyPass.modal.codeHelp': 'Code should be 6 digits (numbers only)',
    'verifyPass.modal.verifying': 'Verifying...',
    'verifyPass.modal.verifyAndAllow': 'Verify & Allow Entry',
    
    // Verify Pass - Checkout Modal
    'verifyPass.checkoutModal.title': '🚨 Verify Checkout',
    'verifyPass.checkoutModal.subtitle': 'Cancelled pass - verify using QR or code',
    'verifyPass.checkoutModal.verificationTitle': 'Checkout Verification',
    'verifyPass.checkoutModal.verificationMsg': 'This pass was cancelled. Visitor must show checkout QR code or provide verification code.',
    'verifyPass.checkoutModal.scanCheckoutQR': 'Scan Checkout QR',
    'verifyPass.checkoutModal.scanCheckoutMsg': 'Scan the checkout QR code sent to visitor',
    'verifyPass.checkoutModal.enterCheckoutCode': 'Enter Code',
    'verifyPass.checkoutModal.enterCheckoutCodeMsg': 'Ask visitor for their NEW 6-digit checkout code',
    'verifyPass.checkoutModal.scanCheckoutQRTitle': 'Scan Checkout QR Code',
    'verifyPass.checkoutModal.scanCheckoutQRMsg': 'Ask the visitor to show their checkout QR code. Position it within the camera frame.',
    'verifyPass.checkoutModal.verifyingExit': 'Verifying and recording exit...',
    'verifyPass.checkoutModal.enterNewCode': 'Enter NEW Checkout Verification Code',
    'verifyPass.checkoutModal.newCodeMsg': 'Ask the visitor for their NEW 6-digit verification code sent AFTER cancellation (not the original check-in code).',
    'verifyPass.checkoutModal.checkoutCode': 'Checkout Verification Code',
    'verifyPass.checkoutModal.verifyAndExit': 'Verify & Record Exit',
    
    // Verify Pass - Cancel Modal
    'verifyPass.cancelModal.title': '🚨 Cancel Pass & Record Checkout',
    'verifyPass.cancelModal.subtitle': 'Cancel checked-in pass and proceed with checkout',
    'verifyPass.cancelModal.mustCancel': 'Pass Must Be Cancelled Before Checkout',
    'verifyPass.cancelModal.currentlyCheckedIn': 'This pass is currently checked-in. You can cancel it now and proceed with checkout:',
    'verifyPass.cancelModal.step1': 'Enter cancellation reason below',
    'verifyPass.cancelModal.step2': 'System will generate 1-hour checkout QR',
    'verifyPass.cancelModal.step3': 'Visitor will receive QR via email/WhatsApp',
    'verifyPass.cancelModal.step4': 'Then verify using QR code or verification code to checkout',
    'verifyPass.cancelModal.reasonLabel': 'Cancellation Reason',
    'verifyPass.cancelModal.reasonRequired': '*',
    'verifyPass.cancelModal.reasonPlaceholder': 'Enter reason for cancelling the pass...',
    'verifyPass.cancelModal.reasonNote': 'This reason will be recorded in the system',
    'verifyPass.cancelModal.cancelBtn': 'Cancel',
    'verifyPass.cancelModal.cancelling': 'Cancelling...',
    'verifyPass.cancelModal.confirmBtn': 'Cancel Pass & Proceed to Checkout',
    
    // Verify Pass - Credentials Modal
    'verifyPass.credModal.title': '✅ Pass Cancelled - Checkout Credentials Generated',
    'verifyPass.credModal.successTitle': 'Pass Successfully Cancelled',
    'verifyPass.credModal.successMsg': '1-hour checkout QR code has been generated and sent to visitor\'s WhatsApp/Email.',
    'verifyPass.credModal.checkoutId': 'Checkout ID',
    'verifyPass.credModal.copy': '📋 Copy',
    'verifyPass.credModal.checkoutCodeTitle': '🔐 Checkout Verification Code',
    'verifyPass.credModal.copyCode': '📋 Copy Code',
    'verifyPass.credModal.newCodeWarning': '⚠️ Use this code for checkout verification (NOT the original check-in code)',
    'verifyPass.credModal.validUntil': '⏰ Valid Until',
    'verifyPass.credModal.validFor1Hour': 'Valid for 1 hour only',
    'verifyPass.credModal.closeBtn': 'Close',
    'verifyPass.credModal.proceedBtn': 'Proceed to Checkout',
    
    // Verify Pass - Prompt
    'verifyPass.prompt.denyReason': 'Enter reason for denial:',
    
    // Analytics Page
    'analytics.title': 'Gate Entry Analytics',
    'analytics.subtitle': 'Comprehensive insights and statistics',
    'analytics.refresh': 'Refresh',
    'analytics.export': 'Export',
    'analytics.filterData': 'Filter Analytics Data',
    'analytics.dateFrom': 'Date From',
    'analytics.dateTo': 'Date To',
    'analytics.purpose': 'Purpose',
    'analytics.vehicle': 'Vehicle',
    'analytics.applyFilters': 'Apply Filters',
    'analytics.reset': 'Reset',
    'analytics.checkedInNow': 'Checked In Now',
    'analytics.totalCompleted': 'Total Completed',
    'analytics.cancelled': 'Cancelled',
    'analytics.totalPasses': 'Total Passes',
    'analytics.activeToday': 'Active Today',
    'analytics.completedToday': 'Completed Today',
    'analytics.pending': 'Pending',
    'analytics.expired': 'Expired',
    
    // Analytics - Purpose Options
    'analytics.purpose.meeting': 'Meeting',
    'analytics.purpose.delivery': 'Delivery',
    'analytics.purpose.maintenance': 'Maintenance',
    'analytics.purpose.event': 'Event',
    'analytics.purpose.interview': 'Interview',
    'analytics.purpose.personal': 'Personal',
    'analytics.purpose.other': 'Other',
    
    // Analytics - Status Options
    'analytics.status.created': 'Created',
    'analytics.status.checkedIn': 'Checked In',
    'analytics.status.checkedOut': 'Checked Out',
    'analytics.status.cancelled': 'Cancelled',
    'analytics.status.expired': 'Expired',
    
    // Analytics - Vehicle Options
    'analytics.vehicle.none': 'Without Vehicle',
    'analytics.vehicle.twoWheeler': 'Two Wheeler',
    'analytics.vehicle.fourWheeler': 'Four Wheeler',
    'analytics.vehicle.other': 'Other',
    
    // Analytics - Chart Titles
    'analytics.chart.dailyTrend': 'Daily Visitor Trend (Last 30 Days)',
    'analytics.chart.passesByPurpose': 'Passes by Purpose',
    'analytics.chart.statusDistribution': 'Status Distribution',
    'analytics.chart.vehicleStats': 'Vehicle Statistics',
    'analytics.chart.extensionStats': 'Pass Extension Statistics',
    'analytics.chart.guardPerformance': 'Guard Performance',
    'analytics.chart.topCreators': 'Top Pass Creators',
    'analytics.chart.recentActivity': 'Recent Activity',
    
    // Analytics - Extension Stats
    'analytics.extension.total': 'Total Extensions',
    'analytics.extension.avgPerPass': 'Avg Extensions per Pass',
    'analytics.extension.rate': 'Extension Rate',
    
    // Analytics - Table Headers
    'analytics.table.guardName': 'Guard Name',
    'analytics.table.checkIns': 'Check-ins',
    'analytics.table.checkOuts': 'Check-outs',
    'analytics.table.totalProcessed': 'Total Processed',
    'analytics.table.name': 'Name',
    'analytics.table.department': 'Department',
    'analytics.table.passesCreated': 'Passes Created',
    'analytics.table.passId': 'Pass ID',
    'analytics.table.visitor': 'Visitor',
    'analytics.table.action': 'Action',
    'analytics.table.performedBy': 'Performed By',
    'analytics.table.timestamp': 'Timestamp',
    
    // Analytics - Empty States
    'analytics.empty.noGuardActivity': 'No guard activity yet',
    'analytics.empty.noRecentActivity': 'No recent activity',
    
    // Analytics - Messages
    'analytics.msg.accessDenied': 'Access Denied',
    'analytics.msg.accessDeniedDesc': 'Only Admins can view the Gate Entry Analytics Dashboard.',
    'analytics.msg.redirecting': 'Redirecting to Gate Entry...',
    'analytics.msg.loading': 'Loading analytics...',
    'analytics.msg.errorLoading': 'Error Loading Analytics',
    'analytics.msg.tryAgain': 'Try Again',
    
    // Analytics - CSV Export
    'analytics.csv.title': 'Gate Entry Analytics Report',
    'analytics.csv.generated': 'Generated:',
    'analytics.csv.overviewStats': 'Overview Statistics',
    'analytics.csv.metric': 'Metric',
    'analytics.csv.count': 'Count',
    'analytics.csv.passesByPurpose': 'Passes by Purpose',
    'analytics.csv.purpose': 'Purpose',
    'analytics.csv.guardPerformance': 'Guard Performance',
    'analytics.csv.total': 'Total',
  },
  
  hi: {
    // Common
    'common.selectPurpose': 'उद्देश्य चुनें',
    'common.allStatus': 'सभी स्थिति',
    'common.allDates': 'सभी तिथियाँ',
    'common.allPurposes': 'सभी उद्देश्य',
    'common.allTypes': 'सभी प्रकार',
    'common.enterFullName': 'पूरा नाम दर्ज करें',
    'common.tenDigitNumber': '10-अंकीय नंबर',
    'common.visitorExample': 'visitor@example.com',
    'common.relationExample': 'उदा., मित्र, परिवार, विक्रेता',
    'common.passIdNameMobile': 'पास ID, नाम, मोबाइल, संबंध, वाहन...',
    'common.of': 'में से',
    'common.passes': 'पास',
    
    // Create Pass Page
    'createPass.title': 'आगंतुक पास बनाएं',
    'createPass.subtitle': 'परिसर आगंतुकों के लिए सुरक्षित प्रवेश पास बनाएं',
    'createPass.creatingAs': 'बना रहे हैं:',
    'createPass.parentGuardianOnly': 'केवल माता-पिता/अभिभावक',
    'createPass.visitorInfo': 'आगंतुक जानकारी',
    'createPass.visitorInfoDesc': 'आगंतुक की व्यक्तिगत जानकारी दर्ज करें',
    'createPass.visitorName': 'आगंतुक का नाम',
    'createPass.mobileNumber': 'मोबाइल नंबर',
    'createPass.emailAddress': 'ईमेल पता',
    'createPass.relation': 'रिश्ता',
    'createPass.numberOfPersons': 'व्यक्तियों की संख्या',
    'createPass.totalVisitors': 'कुल आगंतुकों की संख्या (आप सहित)',
    'createPass.visitDetails': 'मुलाकात विवरण',
    'createPass.visitDetailsDesc': 'मुलाकात का कार्यक्रम और उद्देश्य',
    'createPass.purposeOfVisit': 'मुलाकात का उद्देश्य',
    'createPass.visitStartDate': 'मुलाकात शुरू तिथि',
    'createPass.visitEndDate': 'मुलाकात समाप्ति तिथि',
    'createPass.entryTime': 'प्रवेश समय',
    'createPass.vehicleInfo': 'वाहन जानकारी',
    'createPass.vehicleInfoDesc': 'वैकल्पिक वाहन पंजीकरण विवरण',
    'createPass.vehicleType': 'वाहन का प्रकार',
    'createPass.vehicleNumber': 'वाहन नंबर',
    'createPass.vehicleModel': 'वाहन मॉडल',
    'createPass.accommodation': 'आवास',
    'createPass.accommodationDesc': 'बहु-दिवसीय प्रवास के लिए छात्रावास/अपार्टमेंट बुकिंग',
    'createPass.cancel': 'रद्द करें',
    'createPass.createPass': 'पास बनाएं',
    'createPass.creating': 'पास बनाया जा रहा है...',
    'createPass.whatsappNotification': 'आगंतुक को WhatsApp सूचना प्राप्त होगी',
    'createPass.emailNotification': 'QR कोड और पास विवरण ईमेल द्वारा भेजे जाएंगे',
    'createPass.selectGuardian': 'अभिभावक/माता-पिता चुनें',
    'createPass.selectGuardianOption': '-- अभिभावक चुनें --',
    'createPass.selectFromGuardians': 'अपने पंजीकृत अभिभावकों में से चुनें या नीचे मैन्युअल रूप से दर्ज करें',
    'createPass.loadingGuardians': 'आपके अभिभावक लोड हो रहे हैं...',
    'createPass.noGuardiansFound': 'डेटाबेस में कोई अभिभावक नहीं मिला। कृपया नीचे विवरण मैन्युअल रूप से दर्ज करें।',
    'createPass.autoFilled': 'अभिभावक चयन से स्वतः भरा गया',
    'createPass.parentGuardianBadge': 'केवल माता-पिता/अभिभावक',
    'createPass.howManyPeople': 'कितने लोग',
    'createPass.specifyPurpose': 'उद्देश्य निर्दिष्ट करें',
    'createPass.enterPurpose': 'उद्देश्य दर्ज करें',
    'createPass.selectRelation': 'रिश्ता चुनें',
    'createPass.father': 'पिता',
    'createPass.mother': 'माता',
    'createPass.guardian': 'अभिभावक',
    'createPass.parentOther': 'माता-पिता (अन्य)',
    'createPass.multiDayStayDetected': 'बहु-दिवसीय ठहराव का पता चला - नीचे छात्रावास/अपार्टमेंट बुकिंग उपलब्ध',
    'createPass.entry': 'प्रवेश:',
    'createPass.qrActivates': 'QR 5 घंटे पहले सक्रिय हो जाता है',
    'createPass.visitorWillBringVehicle': 'आगंतुक एक वाहन लाएगा',
    'createPass.vehicleNumberExample': 'उदा., DL01AB1234',
    'createPass.vehicleModelExample': 'उदा., Honda City, Yamaha R15',
    'createPass.noVehicleRequired': 'कोई वाहन जानकारी आवश्यक नहीं',
    'createPass.multiDayVisitDetected': 'बहु-दिवसीय यात्रा का पता चला',
    'createPass.visitPeriod': 'यात्रा अवधि:',
    'createPass.qrActivation': 'QR सक्रियण:',
    'createPass.qrExpiry': 'QR समाप्ति:',
    'createPass.bookHostelQuestion': 'क्या आप छात्रावास/अपार्टमेंट बुक करना चाहते हैं?',
    'createPass.yesBooking': '✅ हां, मैं बुक करना चाहता हूं',
    'createPass.browseRooms': 'उपलब्ध कमरों/अपार्टमेंट से ब्राउज़ और बुक करें',
    'createPass.bookingFlowOpens': 'पास बनने के बाद बुकिंग फ्लो खुलेगा',
    'createPass.noSkipBooking': '❌ नहीं, बुकिंग छोड़ें',
    'createPass.continueWithoutBooking': 'आवास बुकिंग के बिना जारी रखें',
    'createPass.duplicateFound': '⚠️ पास नहीं बनाया जा सकता - डुप्लिकेट मिला',
    'createPass.cancelExisting': 'कृपया नया बनाने से पहले मौजूदा पास को रद्द या पूर्ण करें।',
    'createPass.viewExistingPasses': 'मौजूदा पास देखें और प्रबंधित करें →',
    'createPass.checkingDuplicate': 'डुप्लिकेट पास की जांच की जा रही है...',
    'createPass.error': 'त्रुटि',
    // Purpose options - Student
    'createPass.studentPurpose.personal': 'परिवार की मुलाकात',
    'createPass.studentPurpose.meeting': 'छात्र से मुलाकात',
    'createPass.studentPurpose.event': 'विश्वविद्यालय कार्यक्रम',
    'createPass.studentPurpose.emergency': 'आपातकाल',
    'createPass.studentPurpose.other': 'अन्य',
    // Purpose options - General
    'createPass.generalPurpose.meeting': 'मुलाकात',
    'createPass.generalPurpose.personal': 'व्यक्तिगत मुलाकात',
    'createPass.generalPurpose.delivery': 'डिलीवरी',
    'createPass.generalPurpose.event': 'कार्यक्रम',
    'createPass.generalPurpose.vendor': 'विक्रेता/सेवा',
    'createPass.generalPurpose.other': 'अन्य',
    // Vehicle types
    'createPass.vehicleType.two_wheeler': 'दो पहिया',
    'createPass.vehicleType.four_wheeler': 'चार पहिया',
    'createPass.vehicleType.other': 'अन्य',
    'createPass.selectVehicleType': 'वाहन का प्रकार चुनें',
    // Validation errors
    'createPass.err.visitorNameRequired': 'आगंतुक का नाम आवश्यक है',
    'createPass.err.invalidMobile': 'वैध 10-अंकीय मोबाइल नंबर आवश्यक है',
    'createPass.err.invalidEmail': 'कृपया वैध ईमेल पता दर्ज करें',
    'createPass.err.personsMin': 'व्यक्तियों की संख्या कम से कम 1 होनी चाहिए',
    'createPass.err.personsMax': 'व्यक्तियों की संख्या 50 से अधिक नहीं हो सकती',
    'createPass.err.purposeRequired': 'मुलाकात का उद्देश्य आवश्यक है',
    'createPass.err.specifyOther': 'कृपया अन्य उद्देश्य बताएं',
    'createPass.err.datesRequired': 'मुलाकात की तिथियाँ आवश्यक हैं',
    'createPass.err.endDateBeforeStart': 'समाप्ति तिथि प्रारंभ तिथि से पहले नहीं हो सकती',
    'createPass.err.entryTimeRequired': 'प्रवेश समय आवश्यक है',
    'createPass.err.pastTimeNotAllowed': 'प्रवेश समय भूतकाल में नहीं हो सकता। कृपया वर्तमान या भविष्य का समय चुनें।',
    'createPass.err.vehicleNumberRequired': 'वाहन लाने पर वाहन नंबर आवश्यक है',
    'createPass.err.vehicleModelRequired': 'वाहन लाने पर वाहन मॉडल आवश्यक है',
    'createPass.err.accommodationRequired': 'कृपया बताएं कि आप आवास बुक करना चाहते हैं या नहीं',
    // Success modal
    'createPass.successTitle': 'पास सफलतापूर्वक बनाया गया!',
    'createPass.successMessage': 'प्रवेश सत्यापन के लिए यह कोड अपने आगंतुक के साथ साझा करें।',
    'createPass.successMessageHostel': 'अब आगंतुक के लिए आवास बुक करें।',
    'createPass.successPassId': 'पास ID',
    'createPass.successVerifCode': 'सत्यापन कोड',
    'createPass.successOk': 'ठीक है!',
    'createPass.successShareNote': '🔐 सत्यापन कोड अपने आगंतुक के साथ साझा करें',
    'createPass.successWhatsappSent': '📱 WhatsApp भेजा गया',
    'createPass.successEmailSent': '📧 ईमेल भेजी गई',
    // Hostel Booking Flow
    'hostel.title': 'छात्रावास बुकिंग',
    'hostel.multiDayQuestion': 'आपकी यात्रा बहु-दिवसीय है। क्या आपको आवास चाहिए?',
    'hostel.needAccommodation': 'मुझे आवास बुक करना है',
    'hostel.browseHostels': 'उपलब्ध छात्रावास और कमरे देखें',
    'hostel.noAccommodation': 'आवास की आवश्यकता नहीं',
    'hostel.continueWithout': 'छात्रावास बुकिंग के बिना जारी रखें',
    'hostel.selectHostel': 'छात्रावास चुनें',
    'hostel.selectRoom': 'कमरा चुनें',
    'hostel.back': '← वापस',
    'hostel.loadingHostels': 'छात्रावास लोड हो रहे हैं...',
    'hostel.loadingRooms': 'कमरे लोड हो रहे हैं...',
    'hostel.noHostels': 'चयनित तिथियों के लिए कोई छात्रावास उपलब्ध नहीं',
    'hostel.noRooms': 'इस छात्रावास में कोई कमरा उपलब्ध नहीं',
    'hostel.roomsAvailable': 'कमरे उपलब्ध',
    'hostel.room': 'कमरा',
    'hostel.maxGuests': 'अधिकतम',
    'hostel.guests': 'मेहमान',
    'hostel.guest': 'मेहमान',
    'hostel.nights': 'रातें',
    'hostel.night': 'रात',
    'hostel.pricePerNight': '/रात',
    
    // All Passes Page
    'allPasses.title': 'सभी गेट पास',
    'allPasses.adminView': 'व्यवस्थापक दृश्य: सभी गेट पास दिखा रहा है',
    'allPasses.guardView': 'गार्ड दृश्य: सत्यापन के लिए सभी गेट पास दिखा रहा है',
    'allPasses.myPasses': 'मेरे पास: केवल आपके द्वारा बनाए गए पास दिखा रहा है',
    'allPasses.refresh': 'रीफ्रेश करें',
    'allPasses.createNew': 'नया पास बनाएं',
    'allPasses.totalPasses': 'कुल पास',
    'allPasses.activeToday': 'आज सक्रिय',
    'allPasses.pending': 'लंबित',
    'allPasses.completed': 'पूर्ण',
    'allPasses.expired': 'समाप्त',
    'allPasses.filterSearch': 'पास फ़िल्टर और खोजें',
    'allPasses.searchPasses': 'पास खोजें',
    'allPasses.status': 'स्थिति',
    'allPasses.dateRange': 'तिथि सीमा',
    'allPasses.exportCSV': 'CSV में निर्यात करें',
    // Status filter options
    'allPasses.filter.pending': 'लंबित (पूर्ण नहीं)',
    'allPasses.filter.active': 'सक्रिय',
    'allPasses.filter.checkedIn': 'चेक इन',
    'allPasses.filter.completed': 'पूर्ण',
    'allPasses.filter.denied': 'अस्वीकृत',
    'allPasses.filter.expired': 'समाप्त',
    'allPasses.filter.cancelled': 'रद्द',
    'allPasses.filter.today': 'आज',
    'allPasses.filter.upcoming': 'आगामी',
    'allPasses.filter.past': 'पिछले',
    'allPasses.status.created': 'बनाया गया',
    'allPasses.status.checked_in': 'चेक इन',
    'allPasses.status.cancelled': 'रद्द',
    'allPasses.status.checked_out': 'चेक आउट',
    'allPasses.status.expired': 'समाप्त',
    'allPasses.status.pending': 'लंबित',
    'allPasses.status.active': 'सक्रिय',
    'allPasses.status.completed': 'पूर्ण',
    'allPasses.status.denied': 'अस्वीकृत',
    'allPasses.col.passId': 'पास ID',
    'allPasses.col.visitorDetails': 'आगंतुक विवरण',
    'allPasses.col.visitInfo': 'मुलाकात जानकारी',
    'allPasses.col.dateTime': 'तिथि और समय',
    'allPasses.col.status': 'स्थिति',
    'allPasses.col.actions': 'कार्रवाई',
    'allPasses.noPassesFound': 'आपके फ़िल्टर से मेल खाते कोई पास नहीं मिले',
    'allPasses.by': 'द्वारा',
    'allPasses.system': 'सिस्टम',
    'allPasses.persons': 'व्यक्ति',
    'allPasses.multiDayStay': 'बहु-दिवसीय ठहराव:',
    'allPasses.in': '✓ प्रवेश:',
    'allPasses.out': 'निकास:',
    'allPasses.loading': 'गेट पास लोड हो रहे हैं...',
    'allPasses.loadingWait': 'कृपया प्रतीक्षा करें...',
    'allPasses.errorTitle': 'पास लोड करने में त्रुटि',
    'allPasses.tryAgain': 'पुनः प्रयास करें',
    'allPasses.action.viewDetails': 'विवरण देखें',
    'allPasses.action.cancelPass': 'पास रद्द करें',
    'allPasses.action.resendNotif': 'सूचना पुनः भेजें',
    'allPasses.detail.title': 'पास विवरण',
    'allPasses.detail.visitorInfo': 'आगंतुक जानकारी',
    'allPasses.detail.visitInfo': 'मुलाकात जानकारी',
    'allPasses.detail.vehicleInfo': 'वाहन जानकारी',
    'allPasses.detail.stayInfo': 'ठहराव जानकारी',
    'allPasses.detail.entryExitRecords': 'प्रवेश/निकास रेकॉर्ड',
    'allPasses.detail.extensionInfo': 'पास विस्तार जानकारी',
    'allPasses.detail.checkoutQr': 'चेकआउट QR कोड (1 घंटे की वैधता)',
    'allPasses.detail.name': 'नाम:',
    'allPasses.detail.mobile': 'मोबाइल:',
    'allPasses.detail.email': 'ईमेल:',
    'allPasses.detail.relation': 'रिश्ता:',
    'allPasses.detail.persons': 'व्यक्तियों की संख्या:',
    'allPasses.detail.purpose': 'उद्देश्य:',
    'allPasses.detail.visitDate': 'मुलाकात तिथि:',
    'allPasses.detail.endDate': 'समाप्ति तिथि:',
    'allPasses.detail.entryTime': 'प्रवेश समय:',
    'allPasses.detail.exitTime': 'निकास समय:',
    'allPasses.detail.totalDuration': 'कुल समय:',
    'allPasses.detail.qrActivates': 'QR सक्रिय होता है:',
    'allPasses.detail.vehicleNumber': 'वाहन नंबर:',
    'allPasses.detail.vehicleType': 'वाहन प्रकार:',
    'allPasses.detail.vehicleModel': 'वाहन मॉडल:',
    'allPasses.detail.checkInDate': 'चेक-इन तिथि:',
    'allPasses.detail.checkOutDate': 'चेक-आउट तिथि:',
    'allPasses.detail.hostel': 'छात्रावास:',
    'allPasses.detail.roomNumber': 'कमरा नंबर:',
    'allPasses.detail.expires': 'समाप्ति:',
    'allPasses.detail.qrValid1h': '⏰ सिर्फ 1 घंटे के लिए वैध। आगंतुक को 1 घंटे के भीतर परिसर छोड़ना होगा।',
    'allPasses.detail.extended': 'विस्तारित:',
    'allPasses.detail.times': 'बार',
    'allPasses.detail.reason': 'कारण:',
    'allPasses.detail.notProvided': 'नहीं बताया',
    'allPasses.detail.createdAt': 'बनाने की तिथि:',
    'allPasses.detail.createdBy': 'बनाया गया:',
    'allPasses.detail.unknown': 'अज्ञात',
    'allPasses.detail.extendPass': 'पास बढ़ाएं',
    'allPasses.detail.resendNotif': 'सूचना पुनः भेजें',
    'allPasses.detail.close': 'नजदीक',
    'allPasses.cancel.title': 'पास रद्द करें',
    'allPasses.cancel.warning': 'चेतावनी: पास रद्द करने से चेकआउट QR कोड (1 घंटे के लिए वैध) आगंतुक के मोबाइल/ईमेल पर भेजा जाएगा। आगंतुक को 1 घंटे के भीतर परिसर छोड़ना होगा।',
    'allPasses.cancel.passDetails': 'पास विवरण',
    'allPasses.cancel.passId': 'पास ID:',
    'allPasses.cancel.visitor': 'आगंतुक:',
    'allPasses.cancel.mobile': 'मोबाइल:',
    'allPasses.cancel.status': 'स्थिति:',
    'allPasses.cancel.reasonLabel': 'रद्दीकरण का कारण',
    'allPasses.cancel.reasonPlaceholder': 'पास रद्द करने का कारण दर्ज करें...',
    'allPasses.cancel.keepPass': 'नहीं, पास रखें',
    'allPasses.cancel.confirm': 'हाँ, पास रद्द करें',
    'allPasses.cancel.cancelling': 'रद्द हो रहा है...',
    'allPasses.cancel.successTitle': 'पास सफलतापूर्वक रद्द किया गया!',
    'allPasses.cancel.successMessage': 'आपातकालीन चेकआउट QR और कोड आगंतुक को भेज दिया (1 घंटे के लिए वैध)।',
    'allPasses.cancel.noReason': 'कृपया रद्दीकरण का कारण दर्ज करें',
    'allPasses.cancel.reasonRequired': 'कारण आवश्यक',
    'allPasses.cancel.failedMsg': 'पास रद्द करने में विफल',
    // Cancel Pass - Refund Details (Hindi)
    'allPasses.cancel.beforeCheckIn': 'चेक-इन से पहले रद्द करें',
    'allPasses.cancel.afterCheckIn': 'चेक-इन के बाद रद्द करें (चेकआउट QR)',
    'allPasses.cancel.refundDetails': 'धनवापसी विवरण',
    'allPasses.cancel.originalAmount': 'मूल राशि',
    'allPasses.cancel.cancellationFee': 'रद्दीकरण शुल्क ({percent}%)',
    'allPasses.cancel.refundAmount': 'धनवापसी राशि',
    'allPasses.cancel.hostelBookingInfo': 'हॉस्टल बुकिंग जानकारी',
    'allPasses.cancel.roomNumber': 'कमरा नंबर',
    'allPasses.cancel.hostelName': 'हॉस्टल का नाम',
    'allPasses.cancel.noRefund': 'कोई हॉस्टल बुकिंग नहीं - कोई धनवापसी लागू नहीं',
    'allPasses.cancel.warningBeforeCheckIn': 'नोट: इस पास को अभी तक चेक-इन नहीं किया गया है। रद्द करने से चेकआउट QR कोड नहीं बनेगा।',
    'allPasses.cancel.warningAfterCheckIn': 'चेतावनी: इस पास को रद्द करने से चेकआउट QR कोड बनेगा (1 घंटे के लिए मान्य) जो आगंतुक के मोबाइल/ईमेल पर भेजा जाएगा।',
    'allPasses.cancel.successBeforeCheckIn': 'पास सफलतापूर्वक रद्द किया गया',
    'allPasses.cancel.successWithRefund': 'पास रद्द किया गया। धनवापसी राशि: ₹{amount}',
    'allPasses.cancel.reasonRequiredError': 'रद्दीकरण का कारण आवश्यक है',
    // Resend notification (Hindi)
    'allPasses.resend.title': 'सूचना भेजी गई',
    'allPasses.resend.message': 'सूचना पुनः भेजी गई',
    'extend.title': 'पास बढ़ाएं',
    'extend.note': 'टिप्पणी: समाप्ति तिथि बढ़ाने से पास की समाप्ति नए अंत दिनांक के 23:59 पर अपडेट हो जाएगी।',
    'extend.currentDetails': 'वर्तमान विवरण',
    'extend.passId': 'पास ID:',
    'extend.visitStartDate': 'मुलाकात शुरू तिथि:',
    'extend.currentEndDate': 'वर्तमान अंत तिथि:',
    'extend.entryTime': 'प्रवेश समय:',
    'extend.newEndDate': 'नई अंत तिथि',
    'extend.expireNote': 'पास इस तिथि को 23:59 पर समाप्त होगा',
    'extend.reasonLabel': 'विस्तार का कारण',
    'extend.reasonPlaceholder': 'पास बढ़ाने का कारण दर्ज करें...',
    'extend.cancel': 'रद्द करें',
    'extend.submit': 'पास बढ़ाएं',
    'extend.submitting': 'बढ़ाया जा रहा है...',
    'extend.errNoDate': 'नई अंत तिथि चुनें',
    'extend.errNoReason': 'विस्तार का कारण बताएं',
    'extend.errDateAfter': 'नई अंत तिथि वर्तमान अंत तिथि के बाद होनी चाहिए',
    'extend.errFailed': 'पास बढ़ाने में विफल',
    'extend.successTitle': 'पास बढ़ा दिया गया!',
    'extend.successMsg': 'पास की समाप्ति तिथि सफलतापूर्वक बढ़ा दी गई',
    'common.error': 'त्रुटि',
    
    // Verify Pass Page
    'verifyPass.title': 'पास सत्यापन',
    'verifyPass.subtitle': 'आगंतुक पास सत्यापन और प्रवेश प्रबंधन के लिए गार्ड इंटरफ़ेस',
    'verifyPass.manualSearch': 'मैन्युअल खोज',
    'verifyPass.qrScan': 'QR स्कैन',
    'verifyPass.searchBy': 'इसके द्वारा खोजें',
    'verifyPass.search': 'खोजें',
    'verifyPass.searching': 'खोज रहे हैं...',
    'verifyPass.scannerCamera': 'स्कैनर कैमरा',
    'verifyPass.positionQR': 'QR कोड को कैमरा फ्रेम के भीतर रखें',
    'verifyPass.verifying': 'स्कैन किए गए पास की पुष्टि की जा रही है...',
    'verifyPass.enterPassId': 'पास ID दर्ज करें',
    'verifyPass.passIdPlaceholder': 'UNI-PASS-XXX',
    
    // Verify Pass - Search Options
    'verifyPass.searchOptions.passId': 'पास ID',
    'verifyPass.searchOptions.visitorName': 'आगंतुक का नाम',
    'verifyPass.searchOptions.mobile': 'मोबाइल नंबर',
    'verifyPass.searchOptions.vehicle': 'वाहन नंबर',
    'verifyPass.enterVisitorName': 'आगंतुक का नाम दर्ज करें',
    'verifyPass.enterMobile': 'मोबाइल नंबर दर्ज करें',
    'verifyPass.enterVehicle': 'वाहन नंबर दर्ज करें',
    'verifyPass.placeholderName': 'नाम',
    'verifyPass.placeholderMobile': 'मोबाइल',
    'verifyPass.placeholderVehicle': 'वाहन नं.',
    
    // Verify Pass - Errors
    'verifyPass.err.checkoutQrNotFound': 'चेकआउट QR के लिए पास नहीं मिला',
    'verifyPass.err.passNotFound': 'पास नहीं मिला',
    'verifyPass.err.invalidQR': 'अमान्य QR कोड या पास नहीं मिला',
    'verifyPass.err.searchTermRequired': 'कृपया खोज शब्द दर्ज करें',
    'verifyPass.err.noPassFound': 'आपकी खोज मानदंड से मेल खाने वाला कोई पास नहीं मिला',
    'verifyPass.err.verificationFailed': 'सत्यापन विफल',
    
    // Status Labels
    'status.created': 'बनाया गया',
    'status.pending': 'लंबित',
    'status.active': 'सक्रिय',
    'status.checkedIn': 'चेक इन',
    'status.completed': 'पूर्ण',
    'status.checkedOut': 'चेक आउट',
    'status.cancelled': 'रद्द',
    'status.expired': 'समाप्त',
    'status.denied': 'अस्वीकृत',
    
    // Verify Pass - Toast Notifications
    'verifyPass.toast.checkinSuccess': 'आगंतुक को सफलतापूर्वक चेक किया गया है!',
    'verifyPass.toast.checkinSuccessTitle': 'प्रवेश की अनुमति दी गई',
    'verifyPass.toast.checkinFailed': 'प्रवेश की अनुमति देने में विफल',
    'verifyPass.toast.codeRequired': 'कृपया सत्यापन कोड दर्ज करें',
    'verifyPass.toast.codeRequiredTitle': 'सत्यापन आवश्यक',
    'verifyPass.toast.invalidCode': 'अमान्य सत्यापन कोड। कृपया पुनः प्रयास करें।',
    'verifyPass.toast.invalidCodeTitle': 'सत्यापन विफल',
    'verifyPass.toast.entryDenied': 'पास को अस्वीकृत के रूप में चिह्नित किया गया है',
    'verifyPass.toast.entryDeniedTitle': 'प्रवेश अस्वीकृत',
    'verifyPass.toast.denyFailed': 'प्रवेश अस्वीकार करने में विफल',
    'verifyPass.toast.exitSuccess': 'आगंतुक को सफलतापूर्वक चेक आउट किया गया है!',
    'verifyPass.toast.exitSuccessTitle': 'निकास दर्ज किया गया',
    'verifyPass.toast.exitFailed': 'निकास दर्ज करने में विफल',
    'verifyPass.toast.checkoutSuccessTitle': 'चेकआउट दर्ज किया गया',
    'verifyPass.toast.checkoutFailed': 'चेकआउट दर्ज करने में विफल',
    'verifyPass.toast.checkoutCodeInvalid': 'अमान्य चेकआउट सत्यापन कोड। कृपया रद्द करने के बाद भेजे गए नए कोड का उपयोग करें।',
    'verifyPass.toast.reasonRequired': 'कृपया रद्द करने का कारण दर्ज करें',
    'verifyPass.toast.reasonRequiredTitle': 'कारण आवश्यक',
    'verifyPass.toast.cancelSuccess': 'पास सफलतापूर्वक रद्द किया गया। चेकआउट क्रेडेंशियल तैयार किए गए!',
    'verifyPass.toast.cancelSuccessTitle': 'पास रद्द',
    'verifyPass.toast.cancelFailed': 'पास रद्द करने में विफल',
    'verifyPass.toast.idCopied': 'चेकआउट ID कॉपी किया गया!',
    'verifyPass.toast.codeCopied': 'चेकआउट कोड कॉपी किया गया!',
    'verifyPass.toast.copied': 'कॉपी किया गया',
    'verifyPass.toast.cancelledPassWarning': '⚠️ रद्द किया गया पास - चेकआउट आवश्यक',
    
    // Verify Pass - QR Scanner
    'verifyPass.qr.initializing': 'कैमरा स्कैनर शुरू हो रहा है...',
    'verifyPass.qr.instructions': 'स्कैनिंग निर्देश:',
    'verifyPass.qr.step1': 'कैमरा चयन ड्रॉपडाउन ऊपर दिखाई देगा - अपना कैमरा चुनें',
    'verifyPass.qr.step2': 'कैमरा खोलने के लिए "स्कैनिंग शुरू करें" बटन पर क्लिक करें',
    'verifyPass.qr.step3': 'आगंतुक का गेट पास QR कोड कैमरे के सामने रखें',
    'verifyPass.qr.tip1': 'तेज़ पहचान के लिए अच्छी रोशनी और स्थिर हाथ सुनिश्चित करें',
    'verifyPass.qr.tip2': 'स्कैनर सफल स्कैन के बाद स्वचालित रूप से पास को सत्यापित करेगा',
    'verifyPass.qr.tip3': 'जब ब्राउज़र संकेत दे तो कैमरा अनुमति दें',
    'verifyPass.qr.tip4': 'यदि QR कोड पठनीय नहीं है तो मैनुअल सर्च टैब पर स्विच करें',
    
    // Verify Pass - Details
    'verifyPass.details.passId': 'पास ID',
    'verifyPass.details.visitorInfo': 'आगंतुक जानकारी',
    'verifyPass.details.visitInfo': 'यात्रा जानकारी',
    'verifyPass.details.vehicleInfo': 'वाहन जानकारी',
    'verifyPass.details.additionalInfo': 'अतिरिक्त जानकारी',
    'verifyPass.details.entryExitRecords': 'प्रवेश/निकास रिकॉर्ड',
    'verifyPass.details.guardActions': 'गार्ड कार्रवाई',
    
    // Verify Pass - Fields
    'verifyPass.fields.name': 'नाम',
    'verifyPass.fields.mobile': 'मोबाइल',
    'verifyPass.fields.email': 'ईमेल',
    'verifyPass.fields.idProof': 'पहचान प्रमाण',
    'verifyPass.fields.genderAge': 'लिंग / आयु',
    'verifyPass.fields.years': 'वर्ष',
    'verifyPass.fields.persons': 'व्यक्तियों की संख्या',
    'verifyPass.fields.purpose': 'उद्देश्य',
    'verifyPass.fields.department': 'विभाग',
    'verifyPass.fields.personToMeet': 'मिलने वाला व्यक्ति',
    'verifyPass.fields.visitDate': 'यात्रा तिथि',
    'verifyPass.fields.entryTime': 'प्रवेश समय',
    'verifyPass.fields.qrActivatesAt': 'QR सक्रिय होता है',
    'verifyPass.fields.vehicleNumber': 'वाहन नंबर',
    'verifyPass.fields.vehicleType': 'वाहन प्रकार',
    'verifyPass.fields.vehicleModel': 'वाहन मॉडल',
    'verifyPass.fields.itemsCarrying': 'ले जा रहे सामान',
    'verifyPass.fields.specialInstructions': 'विशेष निर्देश',
    'verifyPass.fields.actualEntryTime': 'वास्तविक प्रवेश समय',
    'verifyPass.fields.actualExitTime': 'वास्तविक निकास समय',
    
    // Verify Pass - Warnings
    'verifyPass.warnings.expiringSoon': '⏰ जल्द समाप्त हो रहा है!',
    'verifyPass.warnings.lessThan15': '⚠️ 15 मिनट से कम',
    'verifyPass.warnings.valid': '✅ वैध',
    'verifyPass.warnings.expired': 'समाप्त हो गया',
    'verifyPass.warnings.remaining': 'शेष',
    'verifyPass.warnings.cancelledAt': 'रद्द किया गया:',
    'verifyPass.warnings.qrNotActive': '⏰ QR कोड अभी सक्रिय नहीं',
    'verifyPass.warnings.qrNotActiveMsg': 'यह QR कोड प्रवेश समय से 5 घंटे पहले सक्रिय होगा',
    'verifyPass.warnings.activationTime': 'सक्रियण समय:',
    'verifyPass.warnings.qrActive': '✅ पास सत्यापित - QR सक्रिय',
    'verifyPass.warnings.qrActiveMsg': 'QR कोड सक्रिय है। प्रवेश की अनुमति देने से पहले आगंतुक आईडी प्रमाण और नीचे विवरण सत्यापित करें।',
    'verifyPass.warnings.checkoutRequired': '⚠️ चेकआउट - रद्द किया गया पास',
    'verifyPass.warnings.checkoutMsg': 'यह पास रद्द कर दिया गया है। आगंतुक को 1-घंटे का चेकआउट QR कोड जारी किया गया था।',
    'verifyPass.warnings.checkoutNote': 'आगंतुक की पहचान सत्यापित करें और नीचे "चेकआउट रिकॉर्ड करें" बटन का उपयोग करके निकास की अनुमति दें।',
    'verifyPass.warnings.qrValidity': 'चेकआउट QR वैधता',
    
    // Verify Pass - Actions
    'verifyPass.actions.processing': 'प्रसंस्करण...',
    'verifyPass.actions.recordCheckout': '🚨 चेकआउट रिकॉर्ड करें',
    'verifyPass.actions.qrExpired': '❌ चेकआउट QR समाप्त हो गया - पुनर्जनन के लिए व्यवस्थापक से संपर्क करें',
    'verifyPass.actions.allowEntry': 'प्रवेश की अनुमति दें',
    'verifyPass.actions.qrWillActivate': '⏰ QR प्रवेश समय से 5 घंटे पहले सक्रिय होगा',
    'verifyPass.actions.recordExit': 'निकास रिकॉर्ड करें',
    'verifyPass.actions.denyEntry': 'प्रवेश अस्वीकार करें',
    'verifyPass.actions.alreadyCompleted': '✅ पास पहले ही पूर्ण हो चुका है',
    'verifyPass.actions.passExpired': '⏰ पास समाप्त हो गया',
    'verifyPass.actions.passRejected': '❌ पास अस्वीकार किया गया',
    'verifyPass.actions.noActions': 'ℹ️ कोई कार्रवाई उपलब्ध नहीं',
    
    // Verify Pass - Guard Messages
    'verifyPass.guard.checkoutMsg': '🚨 चेकआउट - आगंतुक निकास रिकॉर्ड करें',
    'verifyPass.guard.allowEntryMsg': '✅ प्रवेश की अनुमति देने से पहले आगंतुक आईडी प्रमाण सत्यापित करें',
    'verifyPass.guard.recordExitMsg': '✅ पुष्टि करें कि आगंतुक परिसर छोड़ रहा है',
    'verifyPass.guard.denyEntryMsg': '⚠️ यदि सत्यापन विफल हो तो प्रवेश अस्वीकार करें',
    'verifyPass.guard.noActionsMsg': 'ℹ️ कोई कार्रवाई उपलब्ध नहीं - पास पहले ही प्रक्रियाबद्ध हो चुका है',
    
    // Verify Pass - Verification Modal
    'verifyPass.modal.verifyIdentity': '🔐 आगंतुक की पहचान सत्यापित करें',
    'verifyPass.modal.chooseMethod': 'सत्यापन विधि चुनें',
    'verifyPass.modal.identityRequired': 'आगंतुक पहचान सत्यापन आवश्यक',
    'verifyPass.modal.identityMsg': 'प्रवेश की अनुमति देने से पहले, नीचे दिए गए तरीकों में से किसी एक का उपयोग करके आगंतुक की पहचान सत्यापित करें।',
    'verifyPass.modal.scanQR': 'QR कोड स्कैन करें',
    'verifyPass.modal.scanQRMsg': 'आगंतुक से अपने गेट पास से QR कोड दिखाने को कहें',
    'verifyPass.modal.openCamera': 'कैमरा खोलें',
    'verifyPass.modal.enterCode': 'कोड दर्ज करें',
    'verifyPass.modal.enterCodeMsg': 'आगंतुक से उनका 6-अंकीय सत्यापन कोड मांगें',
    'verifyPass.modal.backToOptions': '← विकल्पों पर वापस जाएं',
    'verifyPass.modal.scanVisitorQR': 'आगंतुक का QR कोड स्कैन करें',
    'verifyPass.modal.positionQR': 'आगंतुक से अपना गेट पास QR कोड दिखाने को कहें। इसे कैमरा फ्रेम के भीतर रखें।',
    'verifyPass.modal.verifyingEntry': 'सत्यापन और प्रवेश की अनुमति दी जा रही है...',
    'verifyPass.modal.enter6Digit': '6-अंकीय सत्यापन कोड दर्ज करें',
    'verifyPass.modal.ask6Digit': 'आगंतुक से उनके गेट पास के साथ प्राप्त 6-अंकीय कोड प्रदान करने के लिए कहें।',
    'verifyPass.modal.verificationCode': 'सत्यापन कोड',
    'verifyPass.modal.enter6DigitPlaceholder': '6-अंकीय कोड दर्ज करें',
    'verifyPass.modal.codeHelp': 'कोड 6 अंकों (केवल संख्या) का होना चाहिए',
    'verifyPass.modal.verifying': 'सत्यापित किया जा रहा है...',
    'verifyPass.modal.verifyAndAllow': 'सत्यापित करें और प्रवेश की अनुमति दें',
    
    // Verify Pass - Checkout Modal
    'verifyPass.checkoutModal.title': '🚨 चेकआउट सत्यापित करें',
    'verifyPass.checkoutModal.subtitle': 'रद्द किया गया पास - QR या कोड का उपयोग करके सत्यापित करें',
    'verifyPass.checkoutModal.verificationTitle': 'चेकआउट सत्यापन',
    'verifyPass.checkoutModal.verificationMsg': 'यह पास रद्द कर दिया गया था। आगंतुक को चेकआउट QR कोड दिखाना चाहिए या सत्यापन कोड प्रदान करना चाहिए।',
    'verifyPass.checkoutModal.scanCheckoutQR': 'चेकआउट QR स्कैन करें',
    'verifyPass.checkoutModal.scanCheckoutMsg': 'आगंतुक को भेजा गया चेकआउट QR कोड स्कैन करें',
    'verifyPass.checkoutModal.enterCheckoutCode': 'कोड दर्ज करें',
    'verifyPass.checkoutModal.enterCheckoutCodeMsg': 'आगंतुक से उनका नया 6-अंकीय चेकआउट कोड मांगें',
    'verifyPass.checkoutModal.scanCheckoutQRTitle': 'चेकआउट QR कोड स्कैन करें',
    'verifyPass.checkoutModal.scanCheckoutQRMsg': 'आगंतुक से अपना चेकआउट QR कोड दिखाने को कहें। इसे कैमरा फ्रेम के भीतर रखें।',
    'verifyPass.checkoutModal.verifyingExit': 'सत्यापन और निकास रिकॉर्ड किया जा रहा है...',
    'verifyPass.checkoutModal.enterNewCode': 'नया चेकआउट सत्यापन कोड दर्ज करें',
    'verifyPass.checkoutModal.newCodeMsg': 'आगंतुक से रद्द करने के बाद भेजा गया उनका नया 6-अंकीय सत्यापन कोड मांगें (मूल चेक-इन कोड नहीं)।',
    'verifyPass.checkoutModal.checkoutCode': 'चेकआउट सत्यापन कोड',
    'verifyPass.checkoutModal.verifyAndExit': 'सत्यापित करें और निकास रिकॉर्ड करें',
    
    // Verify Pass - Cancel Modal
    'verifyPass.cancelModal.title': '🚨 पास रद्द करें और चेकआउट रिकॉर्ड करें',
    'verifyPass.cancelModal.subtitle': 'चेक किए गए पास को रद्द करें और चेकआउट के साथ आगे बढ़ें',
    'verifyPass.cancelModal.mustCancel': 'चेकआउट से पहले पास रद्द किया जाना चाहिए',
    'verifyPass.cancelModal.currentlyCheckedIn': 'यह पास वर्तमान में चेक-इन है। आप इसे अभी रद्द कर सकते हैं और चेकआउट के साथ आगे बढ़ सकते हैं:',
    'verifyPass.cancelModal.step1': 'नीचे रद्द करने का कारण दर्ज करें',
    'verifyPass.cancelModal.step2': 'सिस्टम 1-घंटे का चेकआउट QR तैयार करेगा',
    'verifyPass.cancelModal.step3': 'आगंतुक को ईमेल/व्हाट्सएप के माध्यम से QR प्राप्त होगा',
    'verifyPass.cancelModal.step4': 'फिर चेकआउट के लिए QR कोड या सत्यापन कोड का उपयोग करके सत्यापित करें',
    'verifyPass.cancelModal.reasonLabel': 'रद्द करने का कारण',
    'verifyPass.cancelModal.reasonRequired': '*',
    'verifyPass.cancelModal.reasonPlaceholder': 'पास रद्द करने का कारण दर्ज करें...',
    'verifyPass.cancelModal.reasonNote': 'यह कारण सिस्टम में दर्ज किया जाएगा',
    'verifyPass.cancelModal.cancelBtn': 'रद्द करें',
    'verifyPass.cancelModal.cancelling': 'रद्द किया जा रहा है...',
    'verifyPass.cancelModal.confirmBtn': 'पास रद्द करें और चेकआउट के लिए आगे बढ़ें',
    
    // Verify Pass - Credentials Modal
    'verifyPass.credModal.title': '✅ पास रद्द - चेकआउट क्रेडेंशियल तैयार',
    'verifyPass.credModal.successTitle': 'पास सफलतापूर्वक रद्द किया गया',
    'verifyPass.credModal.successMsg': '1-घंटे का चेकआउट QR कोड तैयार किया गया है और आगंतुक के व्हाट्सएप/ईमेल पर भेजा गया है।',
    'verifyPass.credModal.checkoutId': 'चेकआउट ID',
    'verifyPass.credModal.copy': '📋 कॉपी',
    'verifyPass.credModal.checkoutCodeTitle': '🔐 चेकआउट सत्यापन कोड',
    'verifyPass.credModal.copyCode': '📋 कोड कॉपी करें',
    'verifyPass.credModal.newCodeWarning': '⚠️ चेकआउट सत्यापन के लिए इस कोड का उपयोग करें (मूल चेक-इन कोड नहीं)',
    'verifyPass.credModal.validUntil': '⏰ तक वैध',
    'verifyPass.credModal.validFor1Hour': 'केवल 1 घंटे के लिए वैध',
    'verifyPass.credModal.closeBtn': 'बंद करें',
    'verifyPass.credModal.proceedBtn': 'चेकआउट के लिए आगे बढ़ें',
    
    // Verify Pass - Prompt
    'verifyPass.prompt.denyReason': 'अस्वीकार करने का कारण दर्ज करें:',
    
    // Analytics Page
    'analytics.title': 'गेट एंट्री एनालिटिक्स',
    'analytics.subtitle': 'व्यापक अंतर्दृष्टि और सांख्यिकी',
    'analytics.refresh': 'रीफ्रेश करें',
    'analytics.export': 'निर्यात करें',
    'analytics.filterData': 'एनालिटिक्स डेटा फ़िल्टर करें',
    'analytics.dateFrom': 'तिथि से',
    'analytics.dateTo': 'तिथि तक',
    'analytics.purpose': 'उद्देश्य',
    'analytics.vehicle': 'वाहन',
    'analytics.applyFilters': 'फ़िल्टर लागू करें',
    'analytics.reset': 'रीसेट करें',
    'analytics.checkedInNow': 'अभी चेक इन',
    'analytics.totalCompleted': 'कुल पूर्ण',
    'analytics.cancelled': 'रद्द',
    'analytics.totalPasses': 'कुल पास',
    'analytics.activeToday': 'आज सक्रिय',
    'analytics.completedToday': 'आज पूर्ण',
    'analytics.pending': 'लंबित',
    'analytics.expired': 'समाप्त',
    
    // Analytics - Purpose Options
    'analytics.purpose.meeting': 'मुलाकात',
    'analytics.purpose.delivery': 'डिलीवरी',
    'analytics.purpose.maintenance': 'मरम्मत',
    'analytics.purpose.event': 'कार्यक्रम',
    'analytics.purpose.interview': 'साक्षात्कार',
    'analytics.purpose.personal': 'व्यक्तिगत',
    'analytics.purpose.other': 'अन्य',
    
    // Analytics - Status Options
    'analytics.status.created': 'बनाया गया',
    'analytics.status.checkedIn': 'चेक इन',
    'analytics.status.checkedOut': 'चेक आउट',
    'analytics.status.cancelled': 'रद्द',
    'analytics.status.expired': 'समाप्त',
    
    // Analytics - Vehicle Options
    'analytics.vehicle.none': 'बिना वाहन',
    'analytics.vehicle.twoWheeler': 'दो पहिया',
    'analytics.vehicle.fourWheeler': 'चार पहिया',
    'analytics.vehicle.other': 'अन्य',
    
    // Analytics - Chart Titles
    'analytics.chart.dailyTrend': 'दैनिक आगंतुक प्रवृत्ति (पिछले 30 दिन)',
    'analytics.chart.passesByPurpose': 'उद्देश्य के अनुसार पास',
    'analytics.chart.statusDistribution': 'स्थिति वितरण',
    'analytics.chart.vehicleStats': 'वाहन सांख्यिकी',
    'analytics.chart.extensionStats': 'पास विस्तार सांख्यिकी',
    'analytics.chart.guardPerformance': 'गार्ड प्रदर्शन',
    'analytics.chart.topCreators': 'शीर्ष पास निर्माता',
    'analytics.chart.recentActivity': 'हालिया गतिविधि',
    
    // Analytics - Extension Stats
    'analytics.extension.total': 'कुल विस्तार',
    'analytics.extension.avgPerPass': 'प्रति पास औसत विस्तार',
    'analytics.extension.rate': 'विस्तार दर',
    
    // Analytics - Table Headers
    'analytics.table.guardName': 'गार्ड का नाम',
    'analytics.table.checkIns': 'चेक-इन',
    'analytics.table.checkOuts': 'चेक-आउट',
    'analytics.table.totalProcessed': 'कुल प्रोसेस किए गए',
    'analytics.table.name': 'नाम',
    'analytics.table.department': 'विभाग',
    'analytics.table.passesCreated': 'बनाए गए पास',
    'analytics.table.passId': 'पास ID',
    'analytics.table.visitor': 'आगंतुक',
    'analytics.table.action': 'कार्रवाई',
    'analytics.table.performedBy': 'द्वारा किया गया',
    'analytics.table.timestamp': 'समय',
    
    // Analytics - Empty States
    'analytics.empty.noGuardActivity': 'अभी तक कोई गार्ड गतिविधि नहीं',
    'analytics.empty.noRecentActivity': 'कोई हालिया गतिविधि नहीं',
    
    // Analytics - Messages
    'analytics.msg.accessDenied': 'पहुंच अस्वीकृत',
    'analytics.msg.accessDeniedDesc': 'केवल एडमिन ही गेट एंट्री एनालिटिक्स डैशबोर्ड देख सकते हैं।',
    'analytics.msg.redirecting': 'गेट एंट्री पर पुनर्निर्देशित किया जा रहा है...',
    'analytics.msg.loading': 'एनालिटिक्स लोड हो रही है...',
    'analytics.msg.errorLoading': 'एनालिटिक्स लोड करने में त्रुटि',
    'analytics.msg.tryAgain': 'पुनः प्रयास करें',
    
    // Analytics - CSV Export
    'analytics.csv.title': 'गेट एंट्री एनालिटिक्स रिपोर्ट',
    'analytics.csv.generated': 'उत्पन्न:',
    'analytics.csv.overviewStats': 'सारांश सांख्यिकी',
    'analytics.csv.metric': 'मीट्रिक',
    'analytics.csv.count': 'गणना',
    'analytics.csv.passesByPurpose': 'उद्देश्य के अनुसार पास',
    'analytics.csv.purpose': 'उद्देश्य',
    'analytics.csv.guardPerformance': 'गार्ड प्रदर्शन',
    'analytics.csv.total': 'कुल',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  // Load saved language from localStorage on mount
  useEffect(() => {
    const savedLang = localStorage.getItem('gateEntryLanguage') as Language;
    if (savedLang && ['en', 'hi'].includes(savedLang)) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('gateEntryLanguage', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
